  /*
  AUTHOR: AMIT KUMAR SINGH
  PROJECT: PHOENIX
  CREATION DATE: 02-JUL-2015
  DESCRIPTION: THIS SQL CODE IS USED TO CREATE LOOK UP TABLES

  REVISION HISTORY:
 -----------------------------------------------------------------------------------------------------
  VERSION    	DATE        	DEVELOPER         		DESCRIPTION
 -----------------------------------------------------------------------------------------------------
    1.0         02-JUL-2015		AMIT					INITIAL DRAFT    
 -----------------------------------------------------------------------------------------------------
*/

CREATE PROCEDURE [dbo].[CreateLUTTables]

AS

BEGIN
------------------------------<TB_XFM_LUT_POOLDATA_LOOKUP>------------------------------
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_XFM_LUT_POOLDATA_LOOKUP]') AND type in (N'U'))
DROP TABLE [dbo].[TB_XFM_LUT_POOLDATA_LOOKUP]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[TB_XFM_LUT_POOLDATA_LOOKUP] 
(
	[ACCOUNT_SOURCE]	[INT] NULL,
	[ACCOUNT_NUMBER]	[INT] NULL,
	[ACC_DESCRIPTION]	[NVARCHAR](255) NULL,
	[POOL_TYPE]	[NVARCHAR](255) NULL,
	[POOL_ID2]	[NVARCHAR](255) NULL,
	[POOL_ID]	[NVARCHAR](255) NULL
)

------------------------------<TB_XFM_LUT_ARRNG_REAS>------------------------------
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_XFM_LUT_ARRNG_REAS]') AND type in (N'U'))
DROP TABLE [dbo].[TB_XFM_LUT_ARRNG_REAS]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[TB_XFM_LUT_ARRNG_REAS] 
(
	[SRC_VAL10_BLK5]	[NVARCHAR](22) NULL,
	[TGT_ARRNG_REAS]	[NVARCHAR](3) NULL
)


------------------------------<TB_XFM_LUT_BACS>------------------------------
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_XFM_LUT_BACS]') AND type in (N'U'))
DROP TABLE [dbo].[TB_XFM_LUT_BACS]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[TB_XFM_LUT_BACS] 
(
	[TGT_NEXTBACSDAY]	[DATE] NULL,
	[SRC_DATE]	[DATE] NULL
)


------------------------------<TB_XFM_LUT_BOOK_FUNDER>------------------------------
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_XFM_LUT_BOOK_FUNDER]') AND type in (N'U'))
DROP TABLE [dbo].[TB_XFM_LUT_BOOK_FUNDER]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[TB_XFM_LUT_BOOK_FUNDER] 
(
	[SRC_BONDID]	[NVARCHAR](255) NULL,
	[TGT_BRAND]	[NVARCHAR](5) NULL,
	[TGT_BOOK]	[NVARCHAR](255) NULL,
	[TGT_ORIG_FUNDERBOOK]	[NVARCHAR](255) NULL,
	[XFM_SOURCE]	[NVARCHAR](255) NULL,
	[TGT_FUNDER]	[NVARCHAR](255) NULL
)


------------------------------<TB_XFM_LUT_BRANCH>------------------------------
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_XFM_LUT_BRANCH]') AND type in (N'U'))
DROP TABLE [dbo].[TB_XFM_LUT_BRANCH]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[TB_XFM_LUT_BRANCH] 
(
	[TGT_BACODE]	[INT] NULL,
	[XFM_HEADOFFICE]	[NVARCHAR](255) NULL,
	[SRC_BRANCH]	[NVARCHAR](255) NULL
)


------------------------------<TB_XFM_LUT_CNTRY_CDE>------------------------------
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_XFM_LUT_CNTRY_CDE]') AND type in (N'U'))
DROP TABLE [dbo].[TB_XFM_LUT_CNTRY_CDE]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[TB_XFM_LUT_CNTRY_CDE] 
(
	[SRC_ADRESES_ADRCOUNTRYCODE]	[NVARCHAR](10) NULL,
	[TGT_CNTRY_CDE]	[NVARCHAR](255) NULL
)


------------------------------<TB_XFM_LUT_DEED_REAS>------------------------------
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_XFM_LUT_DEED_REAS]') AND type in (N'U'))
DROP TABLE [dbo].[TB_XFM_LUT_DEED_REAS]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[TB_XFM_LUT_DEED_REAS] 
(
	[XFM_REDEEM_FLAG]	[NVARCHAR](255) NULL,
	[XFM_DEMAT_FLAG]	[NVARCHAR](255) NULL,
	[SRC_MOVEREASONCODE]	[NVARCHAR](255) NULL,
	[TGT_DEED_REAS]	[INT] NULL,
	[XFM_UNKNOWN_FLAG]	[NVARCHAR](255) NULL
)


------------------------------<TB_XFM_LUT_EMPST>------------------------------
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_XFM_LUT_EMPST]') AND type in (N'U'))
DROP TABLE [dbo].[TB_XFM_LUT_EMPST]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[TB_XFM_LUT_EMPST] 
(
	[SRC_CLIENTS_CLPEMPLOYTYPE]	[NVARCHAR](10) NULL,
	[TGT_CUS01_C01_EMPST]	[NVARCHAR](1) NULL
)


------------------------------<TB_XFM_LUT_FRQPAD>------------------------------
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_XFM_LUT_FRQPAD]') AND type in (N'U'))
DROP TABLE [dbo].[TB_XFM_LUT_FRQPAD]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[TB_XFM_LUT_FRQPAD] 
(
	[SRC_CLIENTS_CLPEARNPAYMETH]	[NVARCHAR](10) NULL,
	[TGT_CUS01_C01_FRQPAD]	[NVARCHAR](255) NULL
)


------------------------------<TB_XFM_LUT_FUNDS_METHOD>------------------------------
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_XFM_LUT_FUNDS_METHOD]') AND type in (N'U'))
DROP TABLE [dbo].[TB_XFM_LUT_FUNDS_METHOD]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[TB_XFM_LUT_FUNDS_METHOD] 
(
	[TGT_FST_REL_MT]	[NVARCHAR](255) NULL,
	[SRC_TRPAYMETHOD]	[NVARCHAR](255) NULL
)


------------------------------<TB_XFM_LUT_HISTORIC_ACNO>------------------------------
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_XFM_LUT_HISTORIC_ACNO]') AND type in (N'U'))
DROP TABLE [dbo].[TB_XFM_LUT_HISTORIC_ACNO]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[TB_XFM_LUT_HISTORIC_ACNO] 
(
	[TGT_HIST_ACNO2]	[NVARCHAR](255) NULL,
	[SRC_ACNO]	[NVARCHAR](255) NULL,
	[TGT_HIST_ACNO1]	[NVARCHAR](255) NULL
)


------------------------------<TB_XFM_LUT_INSURANCE_CONDITION>------------------------------
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_XFM_LUT_INSURANCE_CONDITION]') AND type in (N'U'))
DROP TABLE [dbo].[TB_XFM_LUT_INSURANCE_CONDITION]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[TB_XFM_LUT_INSURANCE_CONDITION] 
(
	[SRC_INSPSCINSCONCODE]	[NVARCHAR](255) NULL,
	[SRC_INSPALINSPACODE]	[NVARCHAR](255) NULL,
	[TGT_INS_OPT]	[NVARCHAR](255) NULL
)


------------------------------<TB_XFM_LUT_INSURANCE_ITEM>------------------------------
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_XFM_LUT_INSURANCE_ITEM]') AND type in (N'U'))
DROP TABLE [dbo].[TB_XFM_LUT_INSURANCE_ITEM]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[TB_XFM_LUT_INSURANCE_ITEM] 
(
	[SRC_INSPSIITEMTYPE]	[NVARCHAR](255) NULL,
	[TGT_SP_ITM_CD]	[INT] NULL
)


------------------------------<TB_XFM_LUT_INSURANCE_PRODUCT>------------------------------
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_XFM_LUT_INSURANCE_PRODUCT]') AND type in (N'U'))
DROP TABLE [dbo].[TB_XFM_LUT_INSURANCE_PRODUCT]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[TB_XFM_LUT_INSURANCE_PRODUCT] 
(
	[SRC_INSPINSTSEQNO]	[INT] NULL,
	[TGT_INS_PROD]	[NVARCHAR](6) NULL
)


------------------------------<TB_XFM_LUT_MARKETING_CHANNEL>------------------------------
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_XFM_LUT_MARKETING_CHANNEL]') AND type in (N'U'))
DROP TABLE [dbo].[TB_XFM_LUT_MARKETING_CHANNEL]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[TB_XFM_LUT_MARKETING_CHANNEL] 
(
	[SRC_APP_A125123]	[NVARCHAR](255) NULL,
	[TGT_MAP_SRC]	[NVARCHAR](255) NULL
)


------------------------------<TB_XFM_LUT_MEDIACODE>------------------------------
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_XFM_LUT_MEDIACODE]') AND type in (N'U'))
DROP TABLE [dbo].[TB_XFM_LUT_MEDIACODE]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[TB_XFM_LUT_MEDIACODE] 
(
	[SRC_APP_A156124]	[NVARCHAR](255) NULL,
	[TGT_MEDCDE]	[NVARCHAR](255) NULL
)


------------------------------<TB_XFM_LUT_MISC>------------------------------
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_XFM_LUT_MISC]') AND type in (N'U'))
DROP TABLE [dbo].[TB_XFM_LUT_MISC]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[TB_XFM_LUT_MISC] 
(
	[SRC_KEY]	[NVARCHAR](255) NULL,
	[TGT_VAL]	[NVARCHAR](255) NULL
)


------------------------------<TB_XFM_LUT_MORTGAGE_REVIEW>------------------------------
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_XFM_LUT_MORTGAGE_REVIEW]') AND type in (N'U'))
DROP TABLE [dbo].[TB_XFM_LUT_MORTGAGE_REVIEW]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[TB_XFM_LUT_MORTGAGE_REVIEW] 
(
	[SRC_HOLDCODE]	[NVARCHAR](255) NULL,
	[TGT_REV_OUT]	[INT] NULL
)


------------------------------<TB_XFM_LUT_MR_ETC>------------------------------
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_XFM_LUT_MR_ETC]') AND type in (N'U'))
DROP TABLE [dbo].[TB_XFM_LUT_MR_ETC]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[TB_XFM_LUT_MR_ETC] 
(
	[SRC_CWCustomer_TITLE]	[INT] NULL,
	[SRC_CLIENTS_CLTITLE]	[NVARCHAR](10) NULL,
	[TGT_C01_MR_ETC]	[NVARCHAR](255) NULL,
	[SRC_TAMAR_CUST_TITLE]	[CHAR](10) NULL
)


------------------------------<TB_XFM_LUT_M_STATUS>------------------------------
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_XFM_LUT_M_STATUS]') AND type in (N'U'))
DROP TABLE [dbo].[TB_XFM_LUT_M_STATUS]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[TB_XFM_LUT_M_STATUS] 
(
	[TGT_C01_M_STATUS]	[NVARCHAR](1) NULL,
	[SRC_CLIENTS_CLPMARITALSTATUS]	[NVARCHAR](10) NULL,
	[SRC_CWCustomer_MARITALSTATUS]	[INT] NULL,
	[SRC_TAMAR_CUST_MARITAL_STATUS]	 [INT] NULL
)


------------------------------<TB_XFM_LUT_NATIONLTY>------------------------------
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_XFM_LUT_NATIONLTY]') AND type in (N'U'))
DROP TABLE [dbo].[TB_XFM_LUT_NATIONLTY]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[TB_XFM_LUT_NATIONLTY] 
(
	[SRC_TAMAR_CUST_COUNTRY_OF_ORIGIN]	[CHAR](2) NULL,
	[SRC_CLIENTS_CLPNATIONALITY]	[NVARCHAR](10) NULL,
	[TGT_NATIONLTY]	[NVARCHAR](255) NULL,
	[SRC_CLIENTS_CLRESIDENCYCODE]	[NVARCHAR](10) NULL,
	[SRC_CWCustomer_NATIONALITY]	[INT] NULL
)


------------------------------<TB_XFM_LUT_NM_SUFFIX>------------------------------
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_XFM_LUT_NM_SUFFIX]') AND type in (N'U'))
DROP TABLE [dbo].[TB_XFM_LUT_NM_SUFFIX]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[TB_XFM_LUT_NM_SUFFIX] 
(
	[SRC_CWCustomer_LETTERS]	[INT] NULL,
	[TGT_NM_SUFFIX]	[NVARCHAR](255) NULL
)


------------------------------<TB_XFM_LUT_NOTETYPE>------------------------------
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_XFM_LUT_NOTETYPE]') AND type in (N'U'))
DROP TABLE [dbo].[TB_XFM_LUT_NOTETYPE]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[TB_XFM_LUT_NOTETYPE] 
(
	[SRC_FLDVAL]	[NVARCHAR](255) NULL,
	[TGT_NOTETYPE]	[NVARCHAR](255) NULL,
	[SRC_SOURCE]	[NVARCHAR](255) NULL
)


------------------------------<TB_XFM_LUT_OCCUPATION>------------------------------
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_XFM_LUT_OCCUPATION]') AND type in (N'U'))
DROP TABLE [dbo].[TB_XFM_LUT_OCCUPATION]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[TB_XFM_LUT_OCCUPATION] 
(
	[TGT_OCCUPATION]	[NVARCHAR](255) NULL,
	[SRC_CLPOCUPATIONCODE]	[NVARCHAR](255) NULL
)


------------------------------<TB_XFM_LUT_OFFER_STATUS>------------------------------
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_XFM_LUT_OFFER_STATUS]') AND type in (N'U'))
DROP TABLE [dbo].[TB_XFM_LUT_OFFER_STATUS]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[TB_XFM_LUT_OFFER_STATUS] 
(
	[SRC_SCR_OFFER_STATUS_SEQ_REF]	[INT] NULL,
	[TGT_OFFER_STATUS]	[INT] NULL
)


------------------------------<TB_XFM_LUT_PENDING_RATECHANGE>------------------------------
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_XFM_LUT_PENDING_RATECHANGE]') AND type in (N'U'))
DROP TABLE [dbo].[TB_XFM_LUT_PENDING_RATECHANGE]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[TB_XFM_LUT_PENDING_RATECHANGE] 
(
	[PEND_REASON_CODE]	[NVARCHAR](255) NULL,
	[PEND_RCCODE]	[NVARCHAR](255) NULL,
	[SRC_ACACNTNO]	[INT] NULL,
	[SRC_EFDATE]	[DATE] NULL,
	[PEND_INTCCODE]	[INT] NULL,
	[SRC_ACSUBACNO]	[INT] NULL,
	[PEND_RATE_CHANGE]	[NVARCHAR](255) NULL,
	[PEND_PRODRATE]	[DECIMAL](20, 6) NULL,
	[PEND_ACTCODE]	[INT] NULL,
	[PEND_RATE]	[DECIMAL](20, 6) NULL
)


------------------------------<TB_XFM_LUT_PRODUCT>------------------------------
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_XFM_LUT_PRODUCT]') AND type in (N'U'))
DROP TABLE [dbo].[TB_XFM_LUT_PRODUCT]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[TB_XFM_LUT_PRODUCT] 
(
	[SRC_ACTCODE]	[NVARCHAR](255) NULL,
	[TGT_PRODRATE]	[DECIMAL](20, 6) NULL,
	[TGT_IFRSCODE]	[NVARCHAR](255) NULL,
	[SRC_RCCODE]	[NVARCHAR](255) NULL,
	[SRC_INTCCODE]	[NVARCHAR](255) NULL,
	[TGT_MPRCODE]	[NVARCHAR](255) NULL,
	[TGT_FLEXRULE]	[INT] NULL,
	[TGT_INTRTECDE]	[INT] NULL,
	[TGT_RATEEXP_FLAG]	[NVARCHAR](255) NULL
)


------------------------------<TB_XFM_LUT_PROP_WARANTY>------------------------------
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_XFM_LUT_PROP_WARANTY]') AND type in (N'U'))
DROP TABLE [dbo].[TB_XFM_LUT_PROP_WARANTY]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[TB_XFM_LUT_PROP_WARANTY] 
(
	[SRC_PROPWARANTYTYPE]	[NVARCHAR](255) NULL,
	[TGT_BSI_SCHEME]	[NVARCHAR](255) NULL,
	[TGT_IS_NHBC]	[NVARCHAR](255) NULL
)


------------------------------<TB_XFM_LUT_PURPOSE>------------------------------
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_XFM_LUT_PURPOSE]') AND type in (N'U'))
DROP TABLE [dbo].[TB_XFM_LUT_PURPOSE]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[TB_XFM_LUT_PURPOSE] 
(
	[TGT_PURPOSE]	[NVARCHAR](255) NULL,
	[SRC_PURPOSECODE]	[NVARCHAR](255) NULL
)


------------------------------<TB_XFM_LUT_RELATIONS>------------------------------
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_XFM_LUT_RELATIONS]') AND type in (N'U'))
DROP TABLE [dbo].[TB_XFM_LUT_RELATIONS]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[TB_XFM_LUT_RELATIONS] 
(
	[SRC_APPOCC_O2646]	[NVARCHAR](255) NULL,
	[TGT_RELATIONS]	[NVARCHAR](255) NULL
)


------------------------------<TB_XFM_LUT_REPO_METHOD>------------------------------
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_XFM_LUT_REPO_METHOD]') AND type in (N'U'))
DROP TABLE [dbo].[TB_XFM_LUT_REPO_METHOD]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[TB_XFM_LUT_REPO_METHOD] 
(
	[SRC_SCR_REPO_METHOD_SEQ_REF]	[INT] NULL,
	[TGT_POSS_METH]	[INT] NULL
)


------------------------------<TB_XFM_LUT_ROOF_TYPE>------------------------------
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_XFM_LUT_ROOF_TYPE]') AND type in (N'U'))
DROP TABLE [dbo].[TB_XFM_LUT_ROOF_TYPE]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[TB_XFM_LUT_ROOF_TYPE] 
(
	[SRC_PROPROF_OR_V46169]	[NVARCHAR](255) NULL,
	[TGT_ROOF_TYPE]	[INT] NULL
)


------------------------------<TB_XFM_LUT_S01_CLASS_TYPE>------------------------------
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_XFM_LUT_S01_CLASS_TYPE]') AND type in (N'U'))
DROP TABLE [dbo].[TB_XFM_LUT_S01_CLASS_TYPE]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[TB_XFM_LUT_S01_CLASS_TYPE] 
(
	[SRC_ACHLDERTYPE]	[NVARCHAR](255) NULL,
	[TGT_CLASS_TYPE]	[INT] NULL
)


------------------------------<TB_XFM_LUT_S01_NEW_CLASS>------------------------------
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_XFM_LUT_S01_NEW_CLASS]') AND type in (N'U'))
DROP TABLE [dbo].[TB_XFM_LUT_S01_NEW_CLASS]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[TB_XFM_LUT_S01_NEW_CLASS] 
(
	[SRC_ACCLAS]	[NVARCHAR](255) NULL,
	[TGT_S01_NEW_CLASS]	[INT] NULL
)


------------------------------<TB_XFM_LUT_S01_PROTYPE>------------------------------
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_XFM_LUT_S01_PROTYPE]') AND type in (N'U'))
DROP TABLE [dbo].[TB_XFM_LUT_S01_PROTYPE]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[TB_XFM_LUT_S01_PROTYPE] 
(
	[TGT_S01_PROTYPE]	[INT] NULL,
	[SRC_PROPTYPECODE]	[NVARCHAR](255) NULL
)


------------------------------<TB_XFM_LUT_SALE_METHOD>------------------------------
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_XFM_LUT_SALE_METHOD]') AND type in (N'U'))
DROP TABLE [dbo].[TB_XFM_LUT_SALE_METHOD]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[TB_XFM_LUT_SALE_METHOD] 
(
	[TGT_SALE_METH]	[INT] NULL,
	[SRC_SCR_SALE_METHOD_SEQ_REF]	[INT] NULL
)


------------------------------<TB_XFM_LUT_SALE_STATUS>------------------------------
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_XFM_LUT_SALE_STATUS]') AND type in (N'U'))
DROP TABLE [dbo].[TB_XFM_LUT_SALE_STATUS]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[TB_XFM_LUT_SALE_STATUS] 
(
	[TGT_SALE_STAT]	[INT] NULL,
	[SRC_SCR_CASE_STATUS_SEQ_REF]	[INT] NULL
)


------------------------------<TB_XFM_LUT_SCHG_REAS>------------------------------
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_XFM_LUT_SCHG_REAS]') AND type in (N'U'))
DROP TABLE [dbo].[TB_XFM_LUT_SCHG_REAS]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[TB_XFM_LUT_SCHG_REAS] 
(
	[TGT_SCHG_REAS]	[NVARCHAR](255) NULL,
	[SRC_SUBCHGCHARGETYPE]	[NVARCHAR](255) NULL
)


------------------------------<TB_XFM_LUT_SCR_BLUE_ACCOUNTNO>------------------------------
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_XFM_LUT_SCR_BLUE_ACCOUNTNO]') AND type in (N'U'))
DROP TABLE [dbo].[TB_XFM_LUT_SCR_BLUE_ACCOUNTNO]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[TB_XFM_LUT_SCR_BLUE_ACCOUNTNO] 
(
	[SRC_SCR_BLUE_ACCOUNT_NO]	[NVARCHAR](255) NULL,
	[TGT_SUMMIT_BLUE_ACACNTNO]	[NVARCHAR](255) NULL
)


------------------------------<TB_XFM_LUT_SEC_TYPE>------------------------------
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_XFM_LUT_SEC_TYPE]') AND type in (N'U'))
DROP TABLE [dbo].[TB_XFM_LUT_SEC_TYPE]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[TB_XFM_LUT_SEC_TYPE] 
(
	[SRC_CFFUNDTYPE]	[NVARCHAR](255) NULL,
	[SRC_COLPROPCHARGENO]	[INT] NULL,
	[TGT_SEC_TYPE]	[NVARCHAR](255) NULL
)


------------------------------<TB_XFM_LUT_SERVICELEVEL>------------------------------
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_XFM_LUT_SERVICELEVEL]') AND type in (N'U'))
DROP TABLE [dbo].[TB_XFM_LUT_SERVICELEVEL]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[TB_XFM_LUT_SERVICELEVEL] 
(
	[TGT_SERV_LEVEL]	[NVARCHAR](255) NULL,
	[SRC_APP_A14179]	[NVARCHAR](255) NULL
)


------------------------------<TB_XFM_LUT_TENURE>------------------------------
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_XFM_LUT_TENURE]') AND type in (N'U'))
DROP TABLE [dbo].[TB_XFM_LUT_TENURE]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[TB_XFM_LUT_TENURE] 
(
	[SRC_PROPTENURECODE]	[NVARCHAR](255) NULL,
	[TGT_TENURE]	[NVARCHAR](255) NULL
)


------------------------------<TB_XFM_LUT_TRACE_AGENT>------------------------------
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_XFM_LUT_TRACE_AGENT]') AND type in (N'U'))
DROP TABLE [dbo].[TB_XFM_LUT_TRACE_AGENT]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[TB_XFM_LUT_TRACE_AGENT] 
(
	[TGT_TA_PROFREF]	[INT] NULL,
	[SRC_SCR_TRACE_COMPANY_SEQ_REF]	[INT] NULL
)


------------------------------<TB_XFM_LUT_TRACE_TYPE>------------------------------
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_XFM_LUT_TRACE_TYPE]') AND type in (N'U'))
DROP TABLE [dbo].[TB_XFM_LUT_TRACE_TYPE]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[TB_XFM_LUT_TRACE_TYPE] 
(
	[TGT_TRACE_TYPE]	[NVARCHAR](255) NULL,
	[SRC_SCR_COUNSELLING_YN]	[NVARCHAR](255) NULL,
	[SRC_SCR_TRACE_YN]	[NVARCHAR](255) NULL
)


------------------------------<TB_XFM_LUT_TX>------------------------------
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_XFM_LUT_TX]') AND type in (N'U'))
DROP TABLE [dbo].[TB_XFM_LUT_TX]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[TB_XFM_LUT_TX] 
(
	[XFM_IS_FINES]	[NVARCHAR](255) NULL,
	[SRC_TRGTRSTYPE]	[NVARCHAR](255) NULL,
	[XFM_IS_INTADJ]	[NVARCHAR](255) NULL,
	[TGT_TRANCODE]	[INT] NULL,
	[SRC_TRTRSCODE]	[NVARCHAR](255) NULL
)


------------------------------<TB_XFM_LUT_USERCODE>------------------------------
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_XFM_LUT_USERCODE]') AND type in (N'U'))
DROP TABLE [dbo].[TB_XFM_LUT_USERCODE]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[TB_XFM_LUT_USERCODE] 
(
	[SRC_SUMMIT_USERCODE]	[NVARCHAR](255) NULL,
	[TGT_USERCODE]	[NVARCHAR](255) NULL
)


------------------------------<TB_XFM_LUT_VALTYPE>------------------------------
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_XFM_LUT_VALTYPE]') AND type in (N'U'))
DROP TABLE [dbo].[TB_XFM_LUT_VALTYPE]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[TB_XFM_LUT_VALTYPE] 
(
	[TGT_VAL_REPTYPE]	[NVARCHAR](255) NULL,
	[TGT_VAL_REAS]	[NVARCHAR](255) NULL,
	[TGT_VAL_TYPE]	[NVARCHAR](255) NULL,
	[SRC_V43120_OR_V4315] [NVARCHAR](255)	 NULL
)


------------------------------<TB_XFM_LUT_WALL_TYPE>------------------------------
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_XFM_LUT_WALL_TYPE]') AND type in (N'U'))
DROP TABLE [dbo].[TB_XFM_LUT_WALL_TYPE]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[TB_XFM_LUT_WALL_TYPE] 
(
	[TGT_WALL_TYPE]	[INT] NULL,
	[SRC_PROPWALS_OR_V42525]	[NVARCHAR](255) NULL
)


------------------------------<TB_XFM_LUT_WRNCDE>------------------------------
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_XFM_LUT_WRNCDE]') AND type in (N'U'))
DROP TABLE [dbo].[TB_XFM_LUT_WRNCDE]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[TB_XFM_LUT_WRNCDE] 
(
	[SRC_HLDLCODE]	[NVARCHAR](255) NULL,
	[SRC_OTHER]	[NVARCHAR](255) NULL,
	[TGT_WRNCDE]	[NVARCHAR](255) NULL,
	[TGT_MAP]	[NVARCHAR](255) NULL
)


------------------------------<TB_XFM_LUT_YEAR_END>------------------------------
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_XFM_LUT_YEAR_END]') AND type in (N'U'))
DROP TABLE [dbo].[TB_XFM_LUT_YEAR_END]

SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[TB_XFM_LUT_YEAR_END] 
(
	[YEAR_END_DATE]	[DATE] NULL
)


END