 /*
  AUTHOR: AMIT KUMAR SINGH
  PROJECT: PHOENIX
  CREATION DATE: 01-JUL-2015
  DESCRIPTION: THIS SQL CODE IS USED TO CREATE SSIS FRAMEWORK TABLES LISTED BELOW
  (BATCHLOG			
  PACKAGE				
  PACKAGEERRORLOG		
  PACKAGEVERSION		
  PACKAGEVARIABLELOG	
  PACKAGETASKLOG		
  PACKAGEVERSION		
  LOGTASKPREEXECUTE	
  LOGTASKPOSTEXECUTE	
  CONSTRAINTS)	AND SPS LOGTASKPREEXECUTE AND LOGTASKPOSTEXECUTE	

  NOTE: HERE FIRST WE ARE DROPPING THE CONTRAINTS AND BECAUSE IT IS REFERED IN SPS AND TABLES . AFTER THAT CREATING THE TABLES TO AVOID ANY COLUMN REFERENCE ERROR WHILE DROPING THESE TABLES.
		CREATING THE SPS LOGTASKPREEXECUTE AND LOGTASKPOSTEXECUTE THEN ADDING REFERENCES AND CREATING CHECK CONSTRAINTS.
		NEED TO MAINTAIN THE SAME ORDER. DO NOT DISTURB THE ORDER OF SCRIPTS.

  REVISION HISTORY:
 -----------------------------------------------------------------------------------------------------
  VERSION    	DATE        	DEVELOPER         		DESCRIPTION
 -----------------------------------------------------------------------------------------------------
    1.0         01-JUL-2015		AMIT					INITIAL DRAFT    
 -----------------------------------------------------------------------------------------------------
*/

IF  EXISTS (SELECT * FROM SYS.FOREIGN_KEYS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[FK_PACKAGEERRORLOG_PACKAGELOG]') AND PARENT_OBJECT_ID = OBJECT_ID(N'[DBO].[PACKAGEERRORLOG]'))
ALTER TABLE [DBO].[PACKAGEERRORLOG] DROP CONSTRAINT [FK_PACKAGEERRORLOG_PACKAGELOG]
GO

IF  EXISTS (SELECT * FROM SYS.FOREIGN_KEYS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[FK_PACKAGELOG_BATCHLOG]') AND PARENT_OBJECT_ID = OBJECT_ID(N'[DBO].[PACKAGELOG]'))
ALTER TABLE [DBO].[PACKAGELOG] DROP CONSTRAINT [FK_PACKAGELOG_BATCHLOG]
GO

IF  EXISTS (SELECT * FROM SYS.FOREIGN_KEYS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[FK_PACKAGELOG_PACKAGEVERSION]') AND PARENT_OBJECT_ID = OBJECT_ID(N'[DBO].[PACKAGELOG]'))
ALTER TABLE [DBO].[PACKAGELOG] DROP CONSTRAINT [FK_PACKAGELOG_PACKAGEVERSION]
GO


IF  EXISTS (SELECT * FROM SYS.FOREIGN_KEYS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[FK_PACKAGETASKLOG_PACKAGELOG]') AND PARENT_OBJECT_ID = OBJECT_ID(N'[DBO].[PACKAGETASKLOG]'))
ALTER TABLE [DBO].[PACKAGETASKLOG] DROP CONSTRAINT [FK_PACKAGETASKLOG_PACKAGELOG]
GO

IF  EXISTS (SELECT * FROM SYS.FOREIGN_KEYS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[FK_PACKAGEVARIABLELOG_PACKAGELOG]') AND PARENT_OBJECT_ID = OBJECT_ID(N'[DBO].[PACKAGEVARIABLELOG]'))
ALTER TABLE [DBO].[PACKAGEVARIABLELOG] DROP CONSTRAINT [FK_PACKAGEVARIABLELOG_PACKAGELOG]
GO

IF  EXISTS (SELECT * FROM SYS.FOREIGN_KEYS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[FK_PACKAGEVERSION_PACKAGE]') AND PARENT_OBJECT_ID = OBJECT_ID(N'[DBO].[PACKAGEVERSION]'))
ALTER TABLE [DBO].[PACKAGEVERSION] DROP CONSTRAINT [FK_PACKAGEVERSION_PACKAGE]
GO

IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[LOGTASKPOSTEXECUTE]') AND TYPE IN (N'P', N'PC'))
DROP PROCEDURE [DBO].[LOGTASKPOSTEXECUTE]
GO

IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[LOGTASKPREEXECUTE]') AND TYPE IN (N'P', N'PC'))
DROP PROCEDURE [DBO].[LOGTASKPREEXECUTE]
GO

IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[LOGVARIABLEVALUECHANGED]') AND TYPE IN (N'P', N'PC'))
DROP PROCEDURE [DBO].[LOGVARIABLEVALUECHANGED]
GO

IF  EXISTS (SELECT * FROM SYS.FOREIGN_KEYS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[FK_PACKAGETASKLOG_PACKAGELOG]') AND PARENT_OBJECT_ID = OBJECT_ID(N'[DBO].[PACKAGETASKLOG]'))
ALTER TABLE [DBO].[PACKAGETASKLOG] DROP CONSTRAINT [FK_PACKAGETASKLOG_PACKAGELOG]
GO

IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[PACKAGETASKLOG]') AND TYPE IN (N'U'))
DROP TABLE [DBO].[PACKAGETASKLOG]
GO

IF  EXISTS (SELECT * FROM SYS.FOREIGN_KEYS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[FK_PACKAGEVARIABLELOG_PACKAGELOG]') AND PARENT_OBJECT_ID = OBJECT_ID(N'[DBO].[PACKAGEVARIABLELOG]'))
ALTER TABLE [DBO].[PACKAGEVARIABLELOG] DROP CONSTRAINT [FK_PACKAGEVARIABLELOG_PACKAGELOG]
GO

IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[PACKAGEVARIABLELOG]') AND TYPE IN (N'U'))
DROP TABLE [DBO].[PACKAGEVARIABLELOG]
GO

IF  EXISTS (SELECT * FROM SYS.FOREIGN_KEYS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[FK_PACKAGEERRORLOG_PACKAGELOG]') AND PARENT_OBJECT_ID = OBJECT_ID(N'[DBO].[PACKAGEERRORLOG]'))
ALTER TABLE [DBO].[PACKAGEERRORLOG] DROP CONSTRAINT [FK_PACKAGEERRORLOG_PACKAGELOG]
GO

IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[PACKAGEERRORLOG]') AND TYPE IN (N'U'))
DROP TABLE [DBO].[PACKAGEERRORLOG]
GO

IF  EXISTS (SELECT * FROM SYS.FOREIGN_KEYS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[FK_PACKAGELOG_BATCHLOG]') AND PARENT_OBJECT_ID = OBJECT_ID(N'[DBO].[PACKAGELOG]'))
ALTER TABLE [DBO].[PACKAGELOG] DROP CONSTRAINT [FK_PACKAGELOG_BATCHLOG]
GO

IF  EXISTS (SELECT * FROM SYS.FOREIGN_KEYS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[FK_PACKAGELOG_PACKAGEVERSION]') AND PARENT_OBJECT_ID = OBJECT_ID(N'[DBO].[PACKAGELOG]'))
ALTER TABLE [DBO].[PACKAGELOG] DROP CONSTRAINT [FK_PACKAGELOG_PACKAGEVERSION]
GO

IF  EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N'[DF__PACKAGELO__START__08EA5793]') AND TYPE = 'D')
ALTER TABLE [DBO].[PACKAGELOG] DROP CONSTRAINT [DF__PACKAGELO__START__08EA5793]
GO

IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[PACKAGELOG]') AND TYPE IN (N'U'))
DROP TABLE [DBO].[PACKAGELOG]
GO

IF  EXISTS (SELECT * FROM SYS.FOREIGN_KEYS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[FK_PACKAGEVERSION_PACKAGE]') AND PARENT_OBJECT_ID = OBJECT_ID(N'[DBO].[PACKAGEVERSION]'))
ALTER TABLE [DBO].[PACKAGEVERSION] DROP CONSTRAINT [FK_PACKAGEVERSION_PACKAGE]
GO

IF  EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N'[DF__PACKAGEVE__ENTER__023D5A04]') AND TYPE = 'D')
ALTER TABLE [DBO].[PACKAGEVERSION] DROP CONSTRAINT [DF__PACKAGEVE__ENTER__023D5A04]
GO

IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[PACKAGEVERSION]') AND TYPE IN (N'U'))
DROP TABLE [DBO].[PACKAGEVERSION]
GO

IF  EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N'[DF__PACKAGE__ENTERED__7F60ED59]') AND TYPE = 'D')
ALTER TABLE [DBO].[PACKAGE] DROP CONSTRAINT [DF__PACKAGE__ENTERED__7F60ED59]
GO

IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[PACKAGE]') AND TYPE IN (N'U'))
DROP TABLE [DBO].[PACKAGE]
GO

IF  EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N'[DF__BATCHLOG__STARTD__060DEAE8]') AND TYPE = 'D')
ALTER TABLE [DBO].[BATCHLOG] DROP CONSTRAINT [DF__BATCHLOG__STARTD__060DEAE8]
GO

IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[BATCHLOG]') AND TYPE IN (N'U'))
DROP TABLE [DBO].[BATCHLOG]
GO

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[BATCHLOG]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [DBO].[BATCHLOG]
(
	[BATCHLOGID] [INT] IDENTITY(1,1) NOT NULL,
	[STARTDATETIME] [DATETIME] NOT NULL CONSTRAINT [DF__BATCHLOG__STARTD__060DEAE8]  DEFAULT (GETDATE()),
	[ENDDATETIME] [DATETIME] NULL,
	[STATUS] [CHAR](1) NOT NULL,
	CONSTRAINT [PK_BATCHLOG] PRIMARY KEY CLUSTERED 
	(
	[BATCHLOGID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[PACKAGE]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [DBO].[PACKAGE]
(
	[PACKAGEID] [INT] IDENTITY(1,1) NOT NULL,
	[PACKAGEGUID] [UNIQUEIDENTIFIER] NOT NULL,
	[PACKAGENAME] [VARCHAR](255) NOT NULL,
	[CREATIONDATE] [DATETIME] NOT NULL,
	[CREATEDBY] [VARCHAR](255) NOT NULL,
	[CHUNKNUMBER] [VARCHAR](02) NULL,
	[ENTEREDDATETIME] [DATETIME] NOT NULL CONSTRAINT [DF__PACKAGE__ENTERED__7F60ED59]  DEFAULT (GETDATE()),
	CONSTRAINT [PK_PACKAGE] PRIMARY KEY CLUSTERED 
	(
	[PACKAGEID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[PACKAGEVERSION]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [DBO].[PACKAGEVERSION]
(
	[PACKAGEVERSIONID] [INT] IDENTITY(1,1) NOT NULL,
	[PACKAGEVERSIONGUID] [UNIQUEIDENTIFIER] NOT NULL,
	[PACKAGEID] [INT] NOT NULL,
	[VERSIONMAJOR] [INT] NOT NULL,
	[VERSIONMINOR] [INT] NOT NULL,
	[VERSIONBUILD] [INT] NOT NULL,
	[VERSIONCOMMENT] [VARCHAR](1000) NOT NULL,
	[ENTEREDDATETIME] [DATETIME] NOT NULL CONSTRAINT [DF__PACKAGEVE__ENTER__023D5A04]  DEFAULT (GETDATE()),
	CONSTRAINT [PK_PACKAGEVERSION] PRIMARY KEY CLUSTERED 
	(
	[PACKAGEVERSIONID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[PACKAGELOG]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [DBO].[PACKAGELOG]
(
	[PACKAGELOGID] [INT] IDENTITY(1,1) NOT NULL,
	[BATCHLOGID] [INT] NOT NULL,
	[PACKAGEVERSIONID] [INT] NOT NULL,
	[EXECUTIONINSTANCEID] [UNIQUEIDENTIFIER] NOT NULL,
	[MACHINENAME] [VARCHAR](64) NOT NULL,
	[USERNAME] [VARCHAR](64) NOT NULL,
	[STARTDATETIME] [DATETIME] NOT NULL CONSTRAINT [DF__PACKAGELO__START__08EA5793]  DEFAULT (GETDATE()),
	[ENDDATETIME] [DATETIME] NULL,
	[STATUS] [CHAR](1) NOT NULL,
	CONSTRAINT [PK_PACKAGELOG] PRIMARY KEY CLUSTERED 
	(
	[PACKAGELOGID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[PACKAGEERRORLOG]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [DBO].[PACKAGEERRORLOG]
(
	[PACKAGEERRORLOGID] [INT] IDENTITY(1,1) NOT NULL,
	[PACKAGELOGID] [INT] NOT NULL,
	[SOURCENAME] [VARCHAR](64) NOT NULL,
	[SOURCEID] [UNIQUEIDENTIFIER] NOT NULL,
	[ERRORCODE] [INT] NULL,
	[ERRORDESCRIPTION] [VARCHAR](2000) NULL,
	[LOGDATETIME] [DATETIME] NOT NULL,
	CONSTRAINT [PK_PACKAGEERRORLOG] PRIMARY KEY CLUSTERED 
	(
	[PACKAGEERRORLOGID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[PACKAGEVARIABLELOG]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [DBO].[PACKAGEVARIABLELOG]
(
	[PACKAGEVARIABLELOGID] [INT] IDENTITY(1,1) NOT NULL,
	[PACKAGELOGID] [INT] NOT NULL,
	[VARIABLENAME] [VARCHAR](255) NOT NULL,
	[VARIABLEVALUE] [VARCHAR](MAX) NOT NULL,
	[LOGDATETIME] [DATETIME] NOT NULL,
	CONSTRAINT [PK_PACKAGEVARIABLELOG] PRIMARY KEY CLUSTERED 
	(
	[PACKAGEVARIABLELOGID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[PACKAGETASKLOG]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [DBO].[PACKAGETASKLOG]
(
	[PACKAGETASKLOGID] [INT] IDENTITY(1,1) NOT NULL,
	[PACKAGELOGID] [INT] NOT NULL,
	[SOURCENAME] [VARCHAR](255) NOT NULL,
	[SOURCEID] [UNIQUEIDENTIFIER] NOT NULL,
	[STARTDATETIME] [DATETIME] NOT NULL,
	[ENDDATETIME] [DATETIME] NULL,
	CONSTRAINT [PK_PACKAGETASKLOG] PRIMARY KEY CLUSTERED 
	(
	[PACKAGETASKLOGID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO


IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[TB_UMSLOAD_STATUS]') AND TYPE IN (N'U'))
BEGIN
CREATE TABLE [DBO].[TB_UMSLOAD_STATUS]
(
      [ID] [INT] IDENTITY(1,1) NOT NULL,
      [PACKAGENAME] [VARCHAR](100) NOT NULL,
      [TABLENAME] [VARCHAR](100) NOT NULL,
      [STATUS] [VARCHAR](50) NOT NULL,
      [STARTTIME] [DATETIME] NOT NULL,
      [ENDTIME] [DATETIME] NOT NULL,
       CONSTRAINT [PK_TB_UMSLOAD_STATUS] PRIMARY KEY CLUSTERED 
      (
      [ID] ASC
      )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO

INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_AC02T','TB_SRC_AC02T','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_AC04E','TB_SRC_AC04E','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_AC09C','TB_SRC_AC09C','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_AC10D','TB_SRC_AC10D','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_ACAS','TB_SRC_ACAS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_ACCOUNT_SOURCE','TB_SRC_ACCOUNT_SOURCE','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_ACCOUNT_TYPE','TB_SRC_ACCOUNT_TYPE','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_ACNTACRUEDINTEREST','TB_SRC_ACNTACRUEDINTEREST','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_ACNTMIRASCLAIMS','TB_SRC_ACNTMIRASCLAIMS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_ACNTNOAUTOALOCATIONS','TB_SRC_ACNTNOAUTOALOCATIONS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_ACNTNOAUTORANGES','TB_SRC_ACNTNOAUTORANGES','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_ACNTSOLIATELNKS','TB_SRC_ACNTSOLIATELNKS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_ACNTSPEHISTORIES','TB_SRC_ACNTSPEHISTORIES','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_ACNTSTATEMENTS','TB_SRC_ACNTSTATEMENTS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_ACNTYPEAFINITYLNKS','TB_SRC_ACNTYPEAFINITYLNKS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_ACNTYPECATEGORIES','TB_SRC_ACNTYPECATEGORIES','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_ACPEDSUBTABLECTRL','TB_SRC_ACPEDSUBTABLECTRL','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_ACTADITIONALDESCRIPTIONS','TB_SRC_ACTADITIONALDESCRIPTIONS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_ACTING_COMPANY','TB_SRC_ACTING_COMPANY','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_AFFCASH','TB_SRC_AFFCASH','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_AFFFEERED','TB_SRC_AFFFEERED','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_AFFPRODAVA','TB_SRC_AFFPRODAVA','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_AFILIATEDINSTITUTIONDTLS','TB_SRC_AFILIATEDINSTITUTIONDTLS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_AFILIATEDPAYLNKS','TB_SRC_AFILIATEDPAYLNKS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_AFINITYSCHEMES','TB_SRC_AFINITYSCHEMES','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_AH42A','TB_SRC_AH42A','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_AH43R','TB_SRC_AH43R','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_AH44D','TB_SRC_AH44D','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_AH46C','TB_SRC_AH46C','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_AH47C','TB_SRC_AH47C','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_AH49C','TB_SRC_AH49C','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_APPCORRREC','TB_SRC_APPCORRREC','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_APPCOT','TB_SRC_APPCOT','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_APPCRED','TB_SRC_APPCRED','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_APPCREDIT','TB_SRC_APPCREDIT','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_APPDEPFREE','TB_SRC_APPDEPFREE','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_APPEQUHEAD','TB_SRC_APPEQUHEAD','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_APPFUNAUD','TB_SRC_APPFUNAUD','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_APPFUNCHAAUD','TB_SRC_APPFUNCHAAUD','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_APPFUNCHQAUD','TB_SRC_APPFUNCHQAUD','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_APPINS','TB_SRC_APPINS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_APPINSADJ','TB_SRC_APPINSADJ','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_APPINSANS','TB_SRC_APPINSANS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_APPINSCON','TB_SRC_APPINSCON','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_APPINSRISK','TB_SRC_APPINSRISK','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_APPINSSPEC','TB_SRC_APPINSSPEC','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_APPINSTEXT','TB_SRC_APPINSTEXT','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_APPOTHBORR','TB_SRC_APPOTHBORR','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_APPSCORE','TB_SRC_APPSCORE','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_APPSCOREAUD','TB_SRC_APPSCOREAUD','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_APPSTAGE','TB_SRC_APPSTAGE','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_APPTRAN','TB_SRC_APPTRAN','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_AREARSACNTEXTRACTS','TB_SRC_AREARSACNTEXTRACTS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_AREARSCTRL','TB_SRC_AREARSCTRL','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_AREARSCTRLETERLNKS','TB_SRC_AREARSCTRLETERLNKS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_AREARSINTEREST','TB_SRC_AREARSINTEREST','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_AREARSLETERS','TB_SRC_AREARSLETERS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_AREARSMONITORS','TB_SRC_AREARSMONITORS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_AREARSTATUS','TB_SRC_AREARSTATUS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_ARSMONHISTS','TB_SRC_ARSMONHISTS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_ARSPLANAPAYELEMENTS','TB_SRC_ARSPLANAPAYELEMENTS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_ARSPLANAPORTIONMENTS','TB_SRC_ARSPLANAPORTIONMENTS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_ARSPLANDTLS','TB_SRC_ARSPLANDTLS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_ARSPLANHDRS','TB_SRC_ARSPLANHDRS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_ASSET_CLASS','TB_SRC_ASSET_CLASS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_ASSET_MANAGER','TB_SRC_ASSET_MANAGER','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_AUCTIONEER','TB_SRC_AUCTIONEER','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_BACSREASONEVENTLNKS','TB_SRC_BACSREASONEVENTLNKS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_BALBANDS','TB_SRC_BALBANDS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_BALTRANAPP','TB_SRC_BALTRANAPP','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_BALTRANILL','TB_SRC_BALTRANILL','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_BINLOCATIONS','TB_SRC_BINLOCATIONS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_BORROWER','TB_SRC_BORROWER','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_BORROWERS_SOLICITOR','TB_SRC_BORROWERS_SOLICITOR','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_BORROWER_STATUS','TB_SRC_BORROWER_STATUS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_BRANCHES','TB_SRC_BRANCHES','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CADRISKPOINTS','TB_SRC_CADRISKPOINTS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CAPTIVE_CLAIM','TB_SRC_CAPTIVE_CLAIM','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CARDS','TB_SRC_CARDS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CAS','TB_SRC_CAS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CASBAND','TB_SRC_CASBAND','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CASE_STATUS','TB_SRC_CASE_STATUS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CASHLTV','TB_SRC_CASHLTV','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CBF_MBF_LINK','TB_SRC_CBF_MBF_LINK','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CBM_APPLICATION_LOG','TB_SRC_CBM_APPLICATION_LOG','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CBM_BOND_ACC_SOURCE_XREF','TB_SRC_CBM_BOND_ACC_SOURCE_XREF','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CBM_BOND_DETAILS','TB_SRC_CBM_BOND_DETAILS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CBM_BOND_STATUS','TB_SRC_CBM_BOND_STATUS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CBM_CB_CUSTOMER','TB_SRC_CBM_CB_CUSTOMER','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CBM_CFS_LEDGER_DETAILS','TB_SRC_CBM_CFS_LEDGER_DETAILS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CBM_COLLECT_ARRANGEMENTS','TB_SRC_CBM_COLLECT_ARRANGEMENTS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CBM_COSTS_RECOVERIES','TB_SRC_CBM_COSTS_RECOVERIES','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CBM_CRM_OI','TB_SRC_CBM_CRM_OI','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CBM_FITCH_EXT','TB_SRC_CBM_FITCH_EXT','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CBM_FRAUD_LIST','TB_SRC_CBM_FRAUD_LIST','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CBM_LATEST_REARRANGEMENTS','TB_SRC_CBM_LATEST_REARRANGEMENTS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CBM_LEDGER_POOL_DETAILS','TB_SRC_CBM_LEDGER_POOL_DETAILS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CBM_MOVEMENTS','TB_SRC_CBM_MOVEMENTS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CBM_MOVEMENTS_CONTROL','TB_SRC_CBM_MOVEMENTS_CONTROL','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CBM_PARAMETERS','TB_SRC_CBM_PARAMETERS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CBM_PARAMETERS_TMP','TB_SRC_CBM_PARAMETERS_TMP','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CBM_PARAM_REF','TB_SRC_CBM_PARAM_REF','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CBM_POOL_DETAILS','TB_SRC_CBM_POOL_DETAILS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CBM_REARRANGEMENTS','TB_SRC_CBM_REARRANGEMENTS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CBM_REJECTS','TB_SRC_CBM_REJECTS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CBM_REJECT_REASON','TB_SRC_CBM_REJECT_REASON','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CBM_REPORT_STATIC_DATA','TB_SRC_CBM_REPORT_STATIC_DATA','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CBM_REPOSSESSIONS','TB_SRC_CBM_REPOSSESSIONS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CBM_TMP_ACCOUNT','TB_SRC_CBM_TMP_ACCOUNT','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CBM_TMP_SEARCH_LIST','TB_SRC_CBM_TMP_SEARCH_LIST','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CBM_TRANSACTION_ANALYSIS','TB_SRC_CBM_TRANSACTION_ANALYSIS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CFS_PRODUCT_REFERENCE','TB_SRC_CFS_PRODUCT_REFERENCE','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CHARITABLEASIGNMENTS','TB_SRC_CHARITABLEASIGNMENTS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CHECKLIST','TB_SRC_CHECKLIST','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CHEQUELNKS','TB_SRC_CHEQUELNKS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CITIBANK_MARKER','TB_SRC_CITIBANK_MARKER','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CLAFSCHLNKS','TB_SRC_CLAFSCHLNKS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CLAIM','TB_SRC_CLAIM','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CLAIM_CHECKLIST','TB_SRC_CLAIM_CHECKLIST','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CLBANKLNKS','TB_SRC_CLBANKLNKS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CLRELATIONSHIPS','TB_SRC_CLRELATIONSHIPS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CODES','TB_SRC_CODES','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_COLATERALFUNDS','TB_SRC_COLATERALFUNDS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CONFIG3','TB_SRC_CONFIG3','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CONVERSIONRATES','TB_SRC_CONVERSIONRATES','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CORRCODE','TB_SRC_CORRCODE','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CORRENC','TB_SRC_CORRENC','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CORRTASK','TB_SRC_CORRTASK','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_COST','TB_SRC_COST','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_COST_IMPORT_HDR','TB_SRC_COST_IMPORT_HDR','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_COST_STAGING_TABLE','TB_SRC_COST_STAGING_TABLE','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CRECART','TB_SRC_CRECART','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CREDIT','TB_SRC_CREDIT','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CREDIT_TYPE','TB_SRC_CREDIT_TYPE','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CURENCIES','TB_SRC_CURENCIES','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CUSCARD','TB_SRC_CUSCARD','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CUSEXPREC','TB_SRC_CUSEXPREC','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CUSEXTLEND','TB_SRC_CUSEXTLEND','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CUSSEL','TB_SRC_CUSSEL','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CUSTALIAS','TB_SRC_CUSTALIAS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CUSTDEP','TB_SRC_CUSTDEP','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CUSTOMER','TB_SRC_CUSTOMER','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CWDEPARTMENTREFERENCEDATA','TB_SRC_CWDEPARTMENTREFERENCEDATA','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CWENUMREFERENCEDATA','TB_SRC_CWENUMREFERENCEDATA','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CWSRCONTLINKEDACCOUNTS','TB_SRC_CWSRCONTLINKEDACCOUNTS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CWTASK','TB_SRC_CWTASK','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CWTASKREFERENCEDATA','TB_SRC_CWTASKREFERENCEDATA','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CWUSERREFERENCEDATA','TB_SRC_CWUSERREFERENCEDATA','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CLIENTWISEDOCUMENTFILENET','TB_SRC_CLIENTWISEDOCUMENTFILENET','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CLIENTWISEEFORMS','TB_SRC_CLIENTWISEEFORMS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_CLIENTWISENETWORKFILES','TB_SRC_CLIENTWISENETWORKFILES','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_DATA_LOAD','TB_SRC_DATA_LOAD','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_DEBIT','TB_SRC_DEBIT','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_DEBIT_TYPE','TB_SRC_DEBIT_TYPE','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_DEDPICKLISTS','TB_SRC_DEDPICKLISTS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_DEDSCHEDULES','TB_SRC_DEDSCHEDULES','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_DEED_STATUS','TB_SRC_DEED_STATUS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_DEFAULTDIARIESTEXTS','TB_SRC_DEFAULTDIARIESTEXTS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_DEFAULT_REASON','TB_SRC_DEFAULT_REASON','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_DENORMALISEDINTERESTDTLS','TB_SRC_DENORMALISEDINTERESTDTLS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_DEPEND','TB_SRC_DEPEND','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_DIARIES','TB_SRC_DIARIES','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_DMI_CLAIM','TB_SRC_DMI_CLAIM','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_DMI_NOTIFICATION','TB_SRC_DMI_NOTIFICATION','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_DOC','TB_SRC_DOC','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_DSCHEDPICKLNKS','TB_SRC_DSCHEDPICKLNKS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_DUPLICATELETERDTLS','TB_SRC_DUPLICATELETERDTLS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_ENDOWMENT_COMPANY','TB_SRC_ENDOWMENT_COMPANY','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_EQUCCJ','TB_SRC_EQUCCJ','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_EQUCONT','TB_SRC_EQUCONT','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_EQUREQT','TB_SRC_EQUREQT','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_EQUSCORE','TB_SRC_EQUSCORE','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_EVENTBALBANDS','TB_SRC_EVENTBALBANDS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_EVENTCHARGECTRLS','TB_SRC_EVENTCHARGECTRLS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_EVENTCHARGES','TB_SRC_EVENTCHARGES','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_EVENTERMBANDS','TB_SRC_EVENTERMBANDS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_EVENTSLETERLNKS','TB_SRC_EVENTSLETERLNKS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_EXCEPTIONEVENTS','TB_SRC_EXCEPTIONEVENTS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_EXPACCDEC','TB_SRC_EXPACCDEC','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_EXPDECISION','TB_SRC_EXPDECISION','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_EXPFBL','TB_SRC_EXPFBL','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_EXPFINDECISION','TB_SRC_EXPFINDECISION','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_EXPFORADD','TB_SRC_EXPFORADD','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_EXPOSUREGROUPS','TB_SRC_EXPOSUREGROUPS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_EXPREASON','TB_SRC_EXPREASON','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_EXPREFCODE','TB_SRC_EXPREFCODE','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_FCAREG','TB_SRC_FCAREG','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_FECTRLS','TB_SRC_FECTRLS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_FEE','TB_SRC_FEE','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_FEEBAND','TB_SRC_FEEBAND','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_FEEREC','TB_SRC_FEEREC','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_FEERED','TB_SRC_FEERED','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_FINAL_STATEMENT','TB_SRC_FINAL_STATEMENT','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_FINAL_STATEMENT_DEBIT','TB_SRC_FINAL_STATEMENT_DEBIT','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_FORWARDING_ADDRESS','TB_SRC_FORWARDING_ADDRESS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_FUNCTIONEVENTLNKS','TB_SRC_FUNCTIONEVENTLNKS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_GC50C','TB_SRC_GC50C','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_GC51C','TB_SRC_GC51C','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_GC52T','TB_SRC_GC52T','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_GC53T','TB_SRC_GC53T','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_GC54T','TB_SRC_GC54T','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_GENDER','TB_SRC_GENDER','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_GLOBALTRANSACTIONLNKS','TB_SRC_GLOBALTRANSACTIONLNKS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_ICICHANGEDATA','TB_SRC_ICICHANGEDATA','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_ICIDATADOWNLOADS','TB_SRC_ICIDATADOWNLOADS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_INCOMPALL','TB_SRC_INCOMPALL','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_INSCLAINSTYP','TB_SRC_INSCLAINSTYP','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_INSCLAQ','TB_SRC_INSCLAQ','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_INSINDEXLNKS','TB_SRC_INSINDEXLNKS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_INSLETNAMEDITEMS','TB_SRC_INSLETNAMEDITEMS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_INSLETRISKS','TB_SRC_INSLETRISKS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_INSPACLNKS','TB_SRC_INSPACLNKS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_INSPOLTYPE','TB_SRC_INSPOLTYPE','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_INSPOSTCODEBANDS','TB_SRC_INSPOSTCODEBANDS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_INSPREMADJUSTS','TB_SRC_INSPREMADJUSTS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_INSPROD','TB_SRC_INSPROD','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_INSTINSPALNKS','TB_SRC_INSTINSPALNKS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_INSTNAMEDITEMS','TB_SRC_INSTNAMEDITEMS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_INSTRISKLNKS','TB_SRC_INSTRISKLNKS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_INSTYPACCTYPE','TB_SRC_INSTYPACCTYPE','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_INSTYPEXT','TB_SRC_INSTYPEXT','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_INSURANCEBANDS','TB_SRC_INSURANCEBANDS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_INSURANCECLAIMS','TB_SRC_INSURANCECLAIMS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_INSURANCECOMISIONRATES','TB_SRC_INSURANCECOMISIONRATES','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_INSURANCECOMISIONTRANS','TB_SRC_INSURANCECOMISIONTRANS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_INSURANCECOMPANIES','TB_SRC_INSURANCECOMPANIES','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_INSURANCECONDITIONS','TB_SRC_INSURANCECONDITIONS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_INSURANCECTRL','TB_SRC_INSURANCECTRL','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_INSURANCELETERS','TB_SRC_INSURANCELETERS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_INSURANCERATES','TB_SRC_INSURANCERATES','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_INSURANCERISKTRANSACTIONS','TB_SRC_INSURANCERISKTRANSACTIONS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_INSURANCETYPEANALYSIS','TB_SRC_INSURANCETYPEANALYSIS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_INSURANCE_PREMIUM','TB_SRC_INSURANCE_PREMIUM','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_INTEREST_FURTHER_ADV','TB_SRC_INTEREST_FURTHER_ADV','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_INTEREST_ORIGINAL_ADV','TB_SRC_INTEREST_ORIGINAL_ADV','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_INTPROD','TB_SRC_INTPROD','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_INTRODUCER','TB_SRC_INTRODUCER','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_LETDESC','TB_SRC_LETDESC','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_LETERCHASINGS','TB_SRC_LETERCHASINGS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_LETERCTRLS','TB_SRC_LETERCTRLS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_LETERDTLS','TB_SRC_LETERDTLS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_LETERFORMATDTLS','TB_SRC_LETERFORMATDTLS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_LETERFORMATHDRS','TB_SRC_LETERFORMATHDRS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_LETERHDRS','TB_SRC_LETERHDRS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_LETERITEMSDEFAULTS','TB_SRC_LETERITEMSDEFAULTS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_LETERPERIODS','TB_SRC_LETERPERIODS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_LETERTYPES','TB_SRC_LETERTYPES','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_LETTER','TB_SRC_LETTER','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_LETTER_SET','TB_SRC_LETTER_SET','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_LIFPOL','TB_SRC_LIFPOL','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_LOG_ACCOUNT_SOURCE','TB_SRC_LOG_ACCOUNT_SOURCE','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_LOG_CUSTOMER','TB_SRC_LOG_CUSTOMER','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_LOG_DEED','TB_SRC_LOG_DEED','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_LOG_DEED_STATUS','TB_SRC_LOG_DEED_STATUS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_LOG_FEE','TB_SRC_LOG_FEE','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_LOG_REMINDER','TB_SRC_LOG_REMINDER','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_LOG_RENEWAL','TB_SRC_LOG_RENEWAL','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_LOG_TITLE','TB_SRC_LOG_TITLE','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_MARITAL_STATUS','TB_SRC_MARITAL_STATUS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_MARLINK','TB_SRC_MARLINK','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_MERGEDACNTLNKS','TB_SRC_MERGEDACNTLNKS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_MERGEDCLAFSCHLNKS','TB_SRC_MERGEDCLAFSCHLNKS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_MERGEDCLIENTS','TB_SRC_MERGEDCLIENTS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_MIG_CALCULATION','TB_SRC_MIG_CALCULATION','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_MIG_CALCULATION_COSTS','TB_SRC_MIG_CALCULATION_COSTS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_MIG_COMPANY','TB_SRC_MIG_COMPANY','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_MIG_NOTIFICATION','TB_SRC_MIG_NOTIFICATION','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_MIG_SPLIT','TB_SRC_MIG_SPLIT','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_MONTH','TB_SRC_MONTH','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_MORTGAGE_TYPE','TB_SRC_MORTGAGE_TYPE','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_MOVEMENTS','TB_SRC_MOVEMENTS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_MOVESCHEDULELNKS','TB_SRC_MOVESCHEDULELNKS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_MV_MAX_BONDS','TB_SRC_MV_MAX_BONDS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_NOMINALCROSREFS','TB_SRC_NOMINALCROSREFS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_NOMINALEXCEPTIONS','TB_SRC_NOMINALEXCEPTIONS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_NOMINALINTERFACELNKS','TB_SRC_NOMINALINTERFACELNKS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_OFFER_STATUS','TB_SRC_OFFER_STATUS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_OLD_AUDIT_TRAIL','TB_SRC_OLD_AUDIT_TRAIL','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_OLD_BORROWERS_SOLICITOR','TB_SRC_OLD_BORROWERS_SOLICITOR','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_OLD_DEBT','TB_SRC_OLD_DEBT','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_OLD_DEBTOR_DATA','TB_SRC_OLD_DEBTOR_DATA','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_OLD_PASSBOOK','TB_SRC_OLD_PASSBOOK','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_OLD_PROPERTY_DATA','TB_SRC_OLD_PROPERTY_DATA','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_OLD_RECORD_DELETION','TB_SRC_OLD_RECORD_DELETION','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_OLD_SECOND_MORTGAGE','TB_SRC_OLD_SECOND_MORTGAGE','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_OUTPAY','TB_SRC_OUTPAY','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_PACKAGE','TB_SRC_PACKAGE','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_PAYCODE','TB_SRC_PAYCODE','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_PAYMENT','TB_SRC_PAYMENT','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_PAYMENTAREARS','TB_SRC_PAYMENTAREARS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_PAYMENTCTRLNKS','TB_SRC_PAYMENTCTRLNKS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_PAYMENTCTRLS','TB_SRC_PAYMENTCTRLS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_PAYMENTHOLIDAYMONTHS','TB_SRC_PAYMENTHOLIDAYMONTHS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_PAYMENT_AGREEMENT','TB_SRC_PAYMENT_AGREEMENT','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_PAYMENT_IMPORT_HDR','TB_SRC_PAYMENT_IMPORT_HDR','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_PAYMENT_STAGING_TABLE','TB_SRC_PAYMENT_STAGING_TABLE','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_PAYMENT_TYPE','TB_SRC_PAYMENT_TYPE','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_PAYOVERIDECTRLS','TB_SRC_PAYOVERIDECTRLS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_PAYOVERIDELEMENTLNKS','TB_SRC_PAYOVERIDELEMENTLNKS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_PAYOVERIDELIMITS','TB_SRC_PAYOVERIDELIMITS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_PAYOVERIDEMONITORS','TB_SRC_PAYOVERIDEMONITORS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_PLAN_TABLE','TB_SRC_PLAN_TABLE','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_POOLDATA_LOOKUP','TB_SRC_POOLDATA_LOOKUP','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_PORT','TB_SRC_PORT','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_PROCASHLINK','TB_SRC_PROCASHLINK','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_PROD','TB_SRC_PROD','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_PRODAVACODE','TB_SRC_PRODAVACODE','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_PRODAVALINK','TB_SRC_PRODAVALINK','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_PRODFEERED','TB_SRC_PRODFEERED','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_PRODFEES','TB_SRC_PRODFEES','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_PRODUND','TB_SRC_PRODUND','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_PROFOFIDS','TB_SRC_PROFOFIDS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_PROPERTIES','TB_SRC_PROPERTIES','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_PROPERTY_IMPORT_HDR','TB_SRC_PROPERTY_IMPORT_HDR','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_PROPERTY_STAGING_TABLE','TB_SRC_PROPERTY_STAGING_TABLE','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_PROPERTY_TYPE','TB_SRC_PROPERTY_TYPE','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_PROPOWN','TB_SRC_PROPOWN','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_PT11D','TB_SRC_PT11D','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_PT12D','TB_SRC_PT12D','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_PT13D','TB_SRC_PT13D','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_PT14A','TB_SRC_PT14A','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_PT15A','TB_SRC_PT15A','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_PT16U','TB_SRC_PT16U','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_PUR','TB_SRC_PUR','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_PURCHASER','TB_SRC_PURCHASER','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_QUOACC','TB_SRC_QUOACC','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_QUOAFF','TB_SRC_QUOAFF','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_QUOCASH','TB_SRC_QUOCASH','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_QUOCREDIT','TB_SRC_QUOCREDIT','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_QUOCUS','TB_SRC_QUOCUS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_QUOCUSEXP','TB_SRC_QUOCUSEXP','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_QUOCUSINC','TB_SRC_QUOCUSINC','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_QUOCUSQ','TB_SRC_QUOCUSQ','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_QUODETS','TB_SRC_QUODETS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_QUOFEERED','TB_SRC_QUOFEERED','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_QUOFEES','TB_SRC_QUOFEES','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_QUOINS','TB_SRC_QUOINS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_QUOINSADJ','TB_SRC_QUOINSADJ','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_QUOINSCON','TB_SRC_QUOINSCON','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_QUOINSRISK','TB_SRC_QUOINSRISK','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_QUONOTES','TB_SRC_QUONOTES','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_QUOPORT','TB_SRC_QUOPORT','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_QUOREASON','TB_SRC_QUOREASON','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_QUORED','TB_SRC_QUORED','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_QUOREP','TB_SRC_QUOREP','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_QUORISKCODE','TB_SRC_QUORISKCODE','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_QUOSUB','TB_SRC_QUOSUB','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_QUOSUBAPLIT','TB_SRC_QUOSUBAPLIT','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_QUOTIER','TB_SRC_QUOTIER','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_RECOVERY','TB_SRC_RECOVERY','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_RECOVERY_TYPE','TB_SRC_RECOVERY_TYPE','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_REDEMPTIONCTRLS','TB_SRC_REDEMPTIONCTRLS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_REMINDER','TB_SRC_REMINDER','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_REMOTE_DIVISION','TB_SRC_REMOTE_DIVISION','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_RENEWAL','TB_SRC_RENEWAL','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_REPAYMENTCTRL','TB_SRC_REPAYMENTCTRL','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_REPAYMENTLETERS','TB_SRC_REPAYMENTLETERS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_REPAYMENT_FURTHER_ADV','TB_SRC_REPAYMENT_FURTHER_ADV','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_REPAYMENT_ORIGINAL_ADV','TB_SRC_REPAYMENT_ORIGINAL_ADV','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_REPO_METHOD','TB_SRC_REPO_METHOD','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_RETFUND','TB_SRC_RETFUND','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_SA21D','TB_SRC_SA21D','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_SA22T','TB_SRC_SA22T','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_SA23T','TB_SRC_SA23T','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_SA24D','TB_SRC_SA24D','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_SA25D','TB_SRC_SA25D','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_SA26D','TB_SRC_SA26D','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_SALE_METHOD','TB_SRC_SALE_METHOD','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_SALE_PORTION','TB_SRC_SALE_PORTION','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_SCHEDULE','TB_SRC_SCHEDULE','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_SCHEME','TB_SRC_SCHEME','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_SECHISTAC01','TB_SRC_SECHISTAC01','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_SECHISTACNTLNKS','TB_SRC_SECHISTACNTLNKS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_SECOND_MORTGAGE','TB_SRC_SECOND_MORTGAGE','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_SECPOLREPORTDATES','TB_SRC_SECPOLREPORTDATES','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_SECTRANSMOVEMENTS','TB_SRC_SECTRANSMOVEMENTS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_SECURITISATIONPOLS','TB_SRC_SECURITISATIONPOLS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_SHORTFALL_TYPE','TB_SRC_SHORTFALL_TYPE','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_SOLIATEBANKLNKS','TB_SRC_SOLIATEBANKLNKS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_SOLIATECONTACTS','TB_SRC_SOLIATECONTACTS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_SOUCONT1','TB_SRC_SOUCONT1','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_SOUCONT2','TB_SRC_SOUCONT2','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_SP20L','TB_SRC_SP20L','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_STANDARD_CLAIM','TB_SRC_STANDARD_CLAIM','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_STGTYPE','TB_SRC_STGTYPE','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_SUBPAY','TB_SRC_SUBPAY','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_SUBPAYSUM','TB_SRC_SUBPAYSUM','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_SURPLUS','TB_SRC_SURPLUS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_SYSTEM_USER','TB_SRC_SYSTEM_USER','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_SYSTEM_VARIABLE','TB_SRC_SYSTEM_VARIABLE','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_TASKHOLD','TB_SRC_TASKHOLD','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_TAXRATES','TB_SRC_TAXRATES','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_TEAMPRODAVA','TB_SRC_TEAMPRODAVA','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_TENURE','TB_SRC_TENURE','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_TIERLEVEL','TB_SRC_TIERLEVEL','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_TITLE','TB_SRC_TITLE','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_TITLE_SCR','TB_SRC_TITLE_SCR','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_TOE','TB_SRC_TOE','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_TRACE_COMPANY','TB_SRC_TRACE_COMPANY','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_TRACE_STATUS','TB_SRC_TRACE_STATUS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_TRANSACTIONTYPES','TB_SRC_TRANSACTIONTYPES','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_TRANSCHARGECTRLS','TB_SRC_TRANSCHARGECTRLS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_TRANSCHARGES','TB_SRC_TRANSCHARGES','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_TRANSIN','TB_SRC_TRANSIN','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_TRANSTERMBANDS','TB_SRC_TRANSTERMBANDS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_UNDCODE1','TB_SRC_UNDCODE1','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_UNDCODE2','TB_SRC_UNDCODE2','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_USERMAN','TB_SRC_USERMAN','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_USERMANAUD','TB_SRC_USERMANAUD','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_VADEQUACIES','TB_SRC_VADEQUACIES','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_VALCOM','TB_SRC_VALCOM','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_VALIDATEBANKACNOS','TB_SRC_VALIDATEBANKACNOS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_VALIDATIONTABLE','TB_SRC_VALIDATIONTABLE','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_VALTYPE','TB_SRC_VALTYPE','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_VALUATION','TB_SRC_VALUATION','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_VARHIST','TB_SRC_VARHIST','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_VARMATRIX','TB_SRC_VARMATRIX','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_VAT_RATE','TB_SRC_VAT_RATE','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_VBRANCHES','TB_SRC_VBRANCHES','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_VCHARGES','TB_SRC_VCHARGES','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_VCHEQUES','TB_SRC_VCHEQUES','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_VEVENTS','TB_SRC_VEVENTS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_VINSDB1','TB_SRC_VINSDB1','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_WF60A','TB_SRC_WF60A','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_WF61D','TB_SRC_WF61D','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_WF62D','TB_SRC_WF62D','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_WF63D','TB_SRC_WF63D','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_WF64D','TB_SRC_WF64D','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_WF65C','TB_SRC_WF65C','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_WF66C','TB_SRC_WF66C','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_WF67C','TB_SRC_WF67C','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_WF68C','TB_SRC_WF68C','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_WF69C','TB_SRC_WF69C','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_WF70D','TB_SRC_WF70D','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_XTRANSINCTRLS','TB_SRC_XTRANSINCTRLS','','','')
INSERT INTO [DBO].[TB_UMSLOAD_STATUS] VALUES('PKG_PX_UM_XTRANSTRANCODES','TB_SRC_XTRANSTRANCODES','','','')


GO


IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[LOGTASKPREEXECUTE]') AND TYPE IN (N'P', N'PC'))
DROP PROCEDURE [DBO].[LOGTASKPREEXECUTE]
GO
CREATE PROCEDURE [DBO].[LOGTASKPREEXECUTE]
(    @PACKAGELOGID INT
    ,@SOURCENAME VARCHAR(64)
    ,@SOURCEID UNIQUEIDENTIFIER
    ,@PACKAGEID UNIQUEIDENTIFIER
)

AS
BEGIN
    SET NOCOUNT ON
    IF @PACKAGEID <> @SOURCEID
        AND @SOURCENAME <> 'SQL_LOGPACKAGESTART'
        AND @SOURCENAME <> 'SQL_LOGPACKAGEEND'
        INSERT INTO DBO.PACKAGETASKLOG (PACKAGELOGID, SOURCENAME, SOURCEID, STARTDATETIME)
        VALUES (@PACKAGELOGID, @SOURCENAME, @SOURCEID, GETDATE())
END
GO

IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[LOGTASKPOSTEXECUTE]') AND TYPE IN (N'P', N'PC'))
DROP PROCEDURE [DBO].[LOGTASKPOSTEXECUTE]
GO
CREATE PROCEDURE [DBO].[LOGTASKPOSTEXECUTE]
(    @PACKAGELOGID INT
    ,@SOURCEID UNIQUEIDENTIFIER
    ,@PACKAGEID UNIQUEIDENTIFIER
)

AS
BEGIN
    SET NOCOUNT ON
    IF @PACKAGEID <> @SOURCEID
        UPDATE DBO.PACKAGETASKLOG 
            SET ENDDATETIME = GETDATE()
            WHERE PACKAGELOGID = @PACKAGELOGID AND SOURCEID = @SOURCEID
                AND ENDDATETIME IS NULL
END

GO

IF NOT EXISTS (SELECT * FROM SYS.FOREIGN_KEYS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[FK_PACKAGEERRORLOG_PACKAGELOG]') AND PARENT_OBJECT_ID = OBJECT_ID(N'[DBO].[PACKAGEERRORLOG]'))
ALTER TABLE [DBO].[PACKAGEERRORLOG]  WITH CHECK ADD  CONSTRAINT [FK_PACKAGEERRORLOG_PACKAGELOG] FOREIGN KEY([PACKAGELOGID])
REFERENCES [DBO].[PACKAGELOG] ([PACKAGELOGID])
GO

IF  EXISTS (SELECT * FROM SYS.FOREIGN_KEYS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[FK_PACKAGEERRORLOG_PACKAGELOG]') AND PARENT_OBJECT_ID = OBJECT_ID(N'[DBO].[PACKAGEERRORLOG]'))
ALTER TABLE [DBO].[PACKAGEERRORLOG] CHECK CONSTRAINT [FK_PACKAGEERRORLOG_PACKAGELOG]
GO

IF NOT EXISTS (SELECT * FROM SYS.FOREIGN_KEYS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[FK_PACKAGELOG_BATCHLOG]') AND PARENT_OBJECT_ID = OBJECT_ID(N'[DBO].[PACKAGELOG]'))
ALTER TABLE [DBO].[PACKAGELOG]  WITH CHECK ADD  CONSTRAINT [FK_PACKAGELOG_BATCHLOG] FOREIGN KEY([BATCHLOGID])
REFERENCES [DBO].[BATCHLOG] ([BATCHLOGID])
GO

IF  EXISTS (SELECT * FROM SYS.FOREIGN_KEYS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[FK_PACKAGELOG_BATCHLOG]') AND PARENT_OBJECT_ID = OBJECT_ID(N'[DBO].[PACKAGELOG]'))
ALTER TABLE [DBO].[PACKAGELOG] CHECK CONSTRAINT [FK_PACKAGELOG_BATCHLOG]
GO

IF NOT EXISTS (SELECT * FROM SYS.FOREIGN_KEYS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[FK_PACKAGELOG_PACKAGEVERSION]') AND PARENT_OBJECT_ID = OBJECT_ID(N'[DBO].[PACKAGELOG]'))
ALTER TABLE [DBO].[PACKAGELOG]  WITH CHECK ADD  CONSTRAINT [FK_PACKAGELOG_PACKAGEVERSION] FOREIGN KEY([PACKAGEVERSIONID])
REFERENCES [DBO].[PACKAGEVERSION] ([PACKAGEVERSIONID])
GO

IF  EXISTS (SELECT * FROM SYS.FOREIGN_KEYS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[FK_PACKAGELOG_PACKAGEVERSION]') AND PARENT_OBJECT_ID = OBJECT_ID(N'[DBO].[PACKAGELOG]'))
ALTER TABLE [DBO].[PACKAGELOG] CHECK CONSTRAINT [FK_PACKAGELOG_PACKAGEVERSION]
GO

IF NOT EXISTS (SELECT * FROM SYS.FOREIGN_KEYS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[FK_PACKAGETASKLOG_PACKAGELOG]') AND PARENT_OBJECT_ID = OBJECT_ID(N'[DBO].[PACKAGETASKLOG]'))
ALTER TABLE [DBO].[PACKAGETASKLOG]  WITH CHECK ADD  CONSTRAINT [FK_PACKAGETASKLOG_PACKAGELOG] FOREIGN KEY([PACKAGELOGID])
REFERENCES [DBO].[PACKAGELOG] ([PACKAGELOGID])
GO

IF  EXISTS (SELECT * FROM SYS.FOREIGN_KEYS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[FK_PACKAGETASKLOG_PACKAGELOG]') AND PARENT_OBJECT_ID = OBJECT_ID(N'[DBO].[PACKAGETASKLOG]'))
ALTER TABLE [DBO].[PACKAGETASKLOG] CHECK CONSTRAINT [FK_PACKAGETASKLOG_PACKAGELOG]
GO

IF NOT EXISTS (SELECT * FROM SYS.FOREIGN_KEYS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[FK_PACKAGEVARIABLELOG_PACKAGELOG]') AND PARENT_OBJECT_ID = OBJECT_ID(N'[DBO].[PACKAGEVARIABLELOG]'))
ALTER TABLE [DBO].[PACKAGEVARIABLELOG]  WITH CHECK ADD  CONSTRAINT [FK_PACKAGEVARIABLELOG_PACKAGELOG] FOREIGN KEY([PACKAGELOGID])
REFERENCES [DBO].[PACKAGELOG] ([PACKAGELOGID])
GO

IF  EXISTS (SELECT * FROM SYS.FOREIGN_KEYS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[FK_PACKAGEVARIABLELOG_PACKAGELOG]') AND PARENT_OBJECT_ID = OBJECT_ID(N'[DBO].[PACKAGEVARIABLELOG]'))
ALTER TABLE [DBO].[PACKAGEVARIABLELOG] CHECK CONSTRAINT [FK_PACKAGEVARIABLELOG_PACKAGELOG]
GO

IF NOT EXISTS (SELECT * FROM SYS.FOREIGN_KEYS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[FK_PACKAGEVERSION_PACKAGE]') AND PARENT_OBJECT_ID = OBJECT_ID(N'[DBO].[PACKAGEVERSION]'))
ALTER TABLE [DBO].[PACKAGEVERSION]  WITH CHECK ADD  CONSTRAINT [FK_PACKAGEVERSION_PACKAGE] FOREIGN KEY([PACKAGEID])
REFERENCES [DBO].[PACKAGE] ([PACKAGEID])
GO

IF  EXISTS (SELECT * FROM SYS.FOREIGN_KEYS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[FK_PACKAGEVERSION_PACKAGE]') AND PARENT_OBJECT_ID = OBJECT_ID(N'[DBO].[PACKAGEVERSION]'))
ALTER TABLE [DBO].[PACKAGEVERSION] CHECK CONSTRAINT [FK_PACKAGEVERSION_PACKAGE]
GO