
CREATE PROCEDURE [dbo].[CreateUDMHTables]

AS

BEGIN
--SDMT TABLE CONTAINS ALL THE SOURCE PACKAGE AND CONTROL PACKAGE INFORMATION WHICH ARE USED BY SDMT APPLICATION.
IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[TB_UDMH_SDMT]') AND TYPE IN (N'U'))
DROP TABLE [DBO].[TB_UDMH_SDMT]

CREATE TABLE [DBO].[TB_UDMH_SDMT](
    [SDM_ID] [INT] IDENTITY(1,1) NOT NULL,
	[SOURCENAME] [VARCHAR](100) NOT NULL,
	[PACKAGE_NAME] [VARCHAR](50) NOT NULL,
	[STAGING_TABLE_NAME] [VARCHAR](50) NOT NULL,
	[CATEGORY] [VARCHAR](30) NULL,
	[SOURCE_LOAD_STATUS] [CHAR](20) NULL,
	[CHUNK_NUMBER] [CHAR](2) NOT NULL,	
	[TRANCHE_NUMBER] [CHAR](2) NOT NULL,
	[ACK_MODULENAME] [VARCHAR](70) NULL,
	[SOURCE_RECEIVED_DATETIME] [DATETIME] NULL,
 CONSTRAINT [PK_TB_UDMH_SDMT] PRIMARY KEY CLUSTERED 
(
	[SDM_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

--INSERTING THE PRE-DATA (SOURCE/CONTROL PACKAGES DETAILS) IN SDMT TABLE
---------------------------------------------------
----INSERT CONTROL RELATED DETAILS INTO SDMT----
---------------------------------------------------
	INSERT [DBO].[TB_UDMH_SDMT] ( [SOURCENAME], [PACKAGE_NAME], [STAGING_TABLE_NAME], [CATEGORY], [SOURCE_LOAD_STATUS], [CHUNK_NUMBER], [TRANCHE_NUMBER], [ACK_MODULENAME], [SOURCE_RECEIVED_DATETIME]) VALUES ( N'.CTL.STA', N'PKG_PX_CTL_START', N'TB_UDMH_CTL', 'CONTROL', NULL, '01', '01', N'.AKCTLS.STA', NULL)
	INSERT [DBO].[TB_UDMH_SDMT] ( [SOURCENAME], [PACKAGE_NAME], [STAGING_TABLE_NAME], [CATEGORY], [SOURCE_LOAD_STATUS], [CHUNK_NUMBER], [TRANCHE_NUMBER], [ACK_MODULENAME], [SOURCE_RECEIVED_DATETIME]) VALUES ( N'.CTL.END', N'PKG_PX_CTL_END', N'TB_UDMH_CTL', 'CONTROL', NULL, '01', '01', N'.AKCTLE.STA', NULL)
	INSERT [DBO].[TB_UDMH_SDMT] ( [SOURCENAME], [PACKAGE_NAME], [STAGING_TABLE_NAME], [CATEGORY], [SOURCE_LOAD_STATUS], [CHUNK_NUMBER], [TRANCHE_NUMBER], [ACK_MODULENAME], [SOURCE_RECEIVED_DATETIME]) VALUES ( N'STATS', N'PKG_PX_STATS', N'TB_UDMH_STATS', 'STATS', NULL, N'00', N'01', NULL, NULL)
---------------------------------------------------
----INSERT SOURCE RELATED DETAILS INTO SDMT----
---------------------------------------------------
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('ACTIVATE_APP.csv','PKG_PX_APP','TB_SRC_APP','SEGMENT',NULL,'01','01','.APP',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('ACTIVATE_APPCUST.csv','PKG_PX_APPCUST','TB_SRC_APPCUST','SEGMENT',NULL,'01','01','.APPCUST',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('ACTIVATE_APPFEES.csv','PKG_PX_APPFEES','TB_SRC_APPFEES','SEGMENT',NULL,'01','01','.APPFEES',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('ACTIVATE_APPINSANS.csv','PKG_PX_APPINSANS','TB_SRC_APPINSANS','SEGMENT',NULL,'01','01','.APPINSANS',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('ACTIVATE_APPOCC.csv','PKG_PX_APPOCC','TB_SRC_APPOCC','SEGMENT',NULL,'01','01','.APPOCC',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('ACTIVATE_APPSUB.csv','PKG_PX_APPSUB','TB_SRC_APPSUB','SEGMENT',NULL,'01','01','.APPSUB',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('ACTIVATE_APPTASK.csv','PKG_PX_APPTASK','TB_SRC_APPTASK','SEGMENT',NULL,'01','01','.APPTASK',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('ACTIVATE_CUSADD.csv','PKG_PX_CUSADD','TB_SRC_CUSADD','SEGMENT',NULL,'01','01','.CUSADD',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('ACTIVATE_CUSEMP.csv','PKG_PX_CUSEMP','TB_SRC_CUSEMP','SEGMENT',NULL,'01','01','.CUSEMP',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('ACTIVATE_CUSEXP.csv','PKG_PX_CUSEXP','TB_SRC_CUSEXP','SEGMENT',NULL,'01','01','.CUSEXP',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('ACTIVATE_CUSINC.csv','PKG_PX_CUSINC','TB_SRC_CUSINC','SEGMENT',NULL,'01','01','.CUSINC',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('ACTIVATE_CUSTASUQ.csv','PKG_PX_CUSTASUQ','TB_SRC_CUSTASUQ','SEGMENT',NULL,'01','01','.CUSTASUQ',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('ACTIVATE_RED.csv','PKG_PX_RED','TB_SRC_RED','SEGMENT',NULL,'01','01','.RED',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('ACTIVATE_STAGEHIST.csv','PKG_PX_STAGEHIST','TB_SRC_STAGEHIST','SEGMENT',NULL,'01','01','.STAGEHIST',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('ACTIVATE_VALHIST.csv','PKG_PX_VALHIST','TB_SRC_VALHIST','SEGMENT',NULL,'01','01','.VALHIST',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('ACTIVATE_ACAS.csv','PKG_PX_ACAS','TB_SRC_ACAS','SEGMENT',NULL,'01','01','.ACAS',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('COLLECT_AH45C.csv','PKG_PX_AH45C','TB_SRC_AH45C','SEGMENT',NULL,'01','01','.AH45C',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('COLLECT_AH48C.csv','PKG_PX_AH48C','TB_SRC_AH48C','SEGMENT',NULL,'01','01','.AH48C',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('COLLECT_AC05C.csv','PKG_PX_AC05C','TB_SRC_AC05C','SEGMENT',NULL,'01','01','.AC05C',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('COLLECT_AC06C.csv','PKG_PX_AC06C','TB_SRC_AC06C','SEGMENT',NULL,'01','01','.AC06C',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('COLLECT_AC03N.csv','PKG_PX_AC03N','TB_SRC_AC03N','SEGMENT',NULL,'01','01','.AC03N',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('COLLECT_AC07C.csv','PKG_PX_AC07C','TB_SRC_AC07C','SEGMENT',NULL,'01','01','.AC07C',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('COLLECT_AC08C.csv','PKG_PX_AC08C','TB_SRC_AC08C','SEGMENT',NULL,'01','01','.AC08C',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('COLLECT_AC01D.csv','PKG_PX_AC01D','TB_SRC_AC01D','SEGMENT',NULL,'01','01','.AC01D',NULL)
--INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('COLLECT_AP10L.csv','PKG_PX_AP10L','TB_SRC_AP10L','SEGMENT',NULL,'01','01','.AP10L',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('COLLECT_AH41D.csv','PKG_PX_AH41D','TB_SRC_AH41D','SEGMENT',NULL,'01','01','.AH41D',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('COLLECT_AA31D.csv','PKG_PX_AA31D','TB_SRC_AA31D','SEGMENT',NULL,'01','01','.AA31D',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('COLLECT_AA32P.csv','PKG_PX_AA32P','TB_SRC_AA32P','SEGMENT',NULL,'01','01','.AA32P',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('COLLECT_AH40L.csv','PKG_PX_AH40L','TB_SRC_AH40L','SEGMENT',NULL,'01','01','.AH40L',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('SUMMIT_AC01.csv','PKG_PX_AC01','TB_SRC_AC01','SEGMENT',NULL,'01','01','.AC01',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('SUMMIT_ACNTLNKS.csv','PKG_PX_ACNTLNKS','TB_SRC_ACNTLNKS','SEGMENT',NULL,'01','01','.ACNTLNKS',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('SUMMIT_ACNTYPES.csv','PKG_PX_ACNTYPES','TB_SRC_ACNTYPES','SEGMENT',NULL,'01','01','.ACNTYPES',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('SUMMIT_ACCPED.csv','PKG_PX_ACCPED','TB_SRC_ACPEDYMD','SEGMENT',NULL,'01','01','.ACCPED',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('SUMMIT_ADRESES.csv','PKG_PX_ADRESES','TB_SRC_ADRESES','SEGMENT',NULL,'01','01','.ADRESES',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('SUMMIT_BANKAC01.csv','PKG_PX_BANKAC01','TB_SRC_BANKAC01','SEGMENT',NULL,'01','01','.BANKAC01',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('SUMMIT_BANKDTLS.csv','PKG_PX_BANKDTLS','TB_SRC_BANKDTLS','SEGMENT',NULL,'01','01','.BANKDTLS',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('SUMMIT_CLIENTS.csv','PKG_PX_CLIENTS','TB_SRC_CLIENTS','SEGMENT',NULL,'01','01','.CLIENTS',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('SUMMIT_CLUSAGECODES.csv','PKG_PX_CLUSAGECODES','TB_SRC_CLUSAGECODES','SEGMENT',NULL,'01','01','.CLUSAGECODES',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('SUMMIT_COLATERALNKS.csv','PKG_PX_COLATERALNKS','TB_SRC_COLATERALNKS','SEGMENT',NULL,'01','01','.COLATERALNKS',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('SUMMIT_FUNDSMOVEEXTRACT.csv','PKG_PX_FUNDSMOVEEXTRACT','TB_SRC_FUNDSMOVEEXTRACT','SEGMENT',NULL,'01','01','.FUNDSMOVEEXTRACT',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('SUMMIT_FUNDSMOVELNKS.csv','PKG_PX_FUNDSMOVELNKS','TB_SRC_FUNDSMOVELNKS','SEGMENT',NULL,'01','01','.FUNDSMOVELNKS',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('SUMMIT_FUNDSMOVEMANDATES.csv','PKG_PX_FUNDSMOVEMANDATES','TB_SRC_FUNDSMOVEMANDATES','SEGMENT',NULL,'01','01','.FUNDSMOVEMANDATES',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('SUMMIT_FUNDSMOVEPAYMENTS.csv','PKG_PX_FUNDSMOVEPAYMENTS','TB_SRC_FUNDSMOVEPAYMENTS','SEGMENT',NULL,'01','01','.FUNDSMOVEPAYMENTS',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('SUMMIT_FUNDSMOVESADJUSTMENTS.csv','PKG_PX_FUNDSMOVESADJUSTMENTS','TB_SRC_FUNDSMOVESADJUSTMENTS','SEGMENT',NULL,'01','01','.FUNDSMOVESADJUSTMENTS',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('SUMMIT_HLDCODES.csv','PKG_PX_HLDCODES','TB_SRC_HLDCODES','SEGMENT',NULL,'01','01','.HLDCODES',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('SUMMIT_HLDLNKS.csv','PKG_PX_HLDLNKS','TB_SRC_HLDLNKS','SEGMENT',NULL,'01','01','.HLDLNKS',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('SUMMIT_INSPINSPALNKS.csv','PKG_PX_INSPINSPALNKS','TB_SRC_INSPINSPALNKS','SEGMENT',NULL,'01','01','.INSPINSPALNKS',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('SUMMIT_INSPSPECIFICONDITIONS.csv','PKG_PX_INSPSPECIFICONDITIONS','TB_SRC_INSPSPECIFICONDITIONS','SEGMENT',NULL,'01','01','.INSPSPECIFICONDITIONS',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('SUMMIT_INSPSPECIFIEDITEMS.csv','PKG_PX_INSPSPECIFIEDITEMS','TB_SRC_INSPSPECIFIEDITEMS','SEGMENT',NULL,'01','01','.INSPSPECIFIEDITEMS',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('SUMMIT_INSURANCEPOLICIES.csv','PKG_PX_INSURANCEPOLICIES','TB_SRC_INSURANCEPOLICIES','SEGMENT',NULL,'01','01','.INSURANCEPOLICIES',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('SUMMIT_INSURANCEPOLICYRISKS.csv','PKG_PX_INSURANCEPOLICYRISKS','TB_SRC_INSURANCEPOLICYRISKS','SEGMENT',NULL,'01','01','.INSURANCEPOLICYRISKS',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('SUMMIT_INSURANCETYPES.csv','PKG_PX_INSURANCETYPES','TB_SRC_INSURANCETYPES','SEGMENT',NULL,'01','01','.INSURANCETYPES',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('SUMMIT_INTERESTRATES.csv','PKG_PX_INTERESTRATES','TB_SRC_INTERESTRATES','SEGMENT',NULL,'01','01','.INTERESTRATES',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('SUMMIT_PAYMENTDTLS.csv','PKG_PX_PAYMENTDTLS','TB_SRC_PAYMENTDTLS','SEGMENT',NULL,'01','01','.PAYMENTDTLS',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('SUMMIT_PAYMENTELEMENTS.csv','PKG_PX_PAYMENTELEMENTS','TB_SRC_PAYMENTELEMENTS','SEGMENT',NULL,'01','01','.PAYMENTELEMENTS',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('SUMMIT_PAYOVERIDES.csv','PKG_PX_PAYOVERIDES','TB_SRC_PAYOVERIDES','SEGMENT',NULL,'01','01','.PAYOVERIDES',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('SUMMIT_REDEMPTIONSTATEMENTS.csv','PKG_PX_REDEMPTIONSTATEMENTS','TB_SRC_REDEMPTIONSTATEMENTS','SEGMENT',NULL,'01','01','.REDEMPTIONSTATEMENTS',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('SUMMIT_SOLIATES.csv','PKG_PX_SOLIATES','TB_SRC_SOLIATES','SEGMENT',NULL,'01','01','.SOLIATES',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('SUMMIT_STANDARDRATES.csv','PKG_PX_STANDARDRATES','TB_SRC_STANDARDRATES','SEGMENT',NULL,'01','01','.STANDARDRATES',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('SUMMIT_SUBSEQUENTCHARGES.csv','PKG_PX_SUBSEQUENTCHARGES','TB_SRC_SUBSEQUENTCHARGES','SEGMENT',NULL,'01','01','.SUBSEQUENTCHARGES',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('SUMMIT_TERMBANDS.csv','PKG_PX_TERMBANDS','TB_SRC_TERMBANDS','SEGMENT',NULL,'01','01','.TERMBANDS',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('SUMMIT_VDIARIES.csv','PKG_PX_VDIARIES','TB_SRC_VDIARIES','SEGMENT',NULL,'01','01','.VDIARIES',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('SUMMIT_VMOVEMENTS.csv','PKG_PX_VMOVEMENTS','TB_SRC_VMOVEMENTS','SEGMENT',NULL,'01','01','.VMOVEMENTS',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('SUMMIT_VPROPERTIES.csv','PKG_PX_VPROPERTIES','TB_SRC_VPROPERTIES','SEGMENT',NULL,'01','01','.VPROPERTIES',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('SUMMIT_VTRANSACTIONS.csv','PKG_PX_VTRANSACTIONS','TB_SRC_VTRANSACTIONS','SEGMENT',NULL,'01','01','.VTRANSACTIONS',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('SUMMIT_INTERESTCTRLS.csv','PKG_PX_INTERESTCTRLS','TB_SRC_INTERESTCTRLS','SEGMENT',NULL,'01','01','.INTERESTCTRL',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('SUMMIT_XTRANSDATAS.csv','PKG_PX_XTRANSDATAS','TB_SRC_XTRANSDATAS','SEGMENT',NULL,'01','01','.XTRANSDATAS',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('CBM_COVERED_BOND_FACT.csv','PKG_PX_CBM_COVERED_BOND_FACT','TB_SRC_CBM_COVERED_BOND_FACT','SEGMENT',NULL,'01','01','.CBM_COVERED_BOND_FACT',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('CBM_POOL_CONTROL.csv','PKG_PX_CBM_POOL_CONTROL','TB_SRC_CBM_POOL_CONTROL','SEGMENT',NULL,'01','01','.CBM_POOL_CONTROL',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('CLIENTWISE_CWContactHistoryMainDetail.csv','PKG_PX_CWCONTACTHISTORYMAINDETAIL','TB_SRC_CWCONTACTHISTORYMAINDETAIL','SEGMENT',NULL,'01','01','.CWCONTACTHISTORYMAINDETAIL',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('CLIENTWISE_CWCustomer.csv','PKG_PX_CWCUSTOMER','TB_SRC_CWCUSTOMER','SEGMENT',NULL,'01','01','.CWCUSTOMER',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('CLIENTWISE_CWMarketingRestrictions.csv','PKG_PX_CWMARKETINGRESTRICTIONS','TB_SRC_CWMARKETINGRESTRICTIONS','SEGMENT',NULL,'01','01','.CWMARKETINGRESTRICTIONS',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('CLIENTWISE_CWOtherContact.csv','PKG_PX_CWOTHERCONTACT','TB_SRC_CWOTHERCONTACT','SEGMENT',NULL,'01','01','.CWOTHERCONTACT',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('CLIENTWISE_CWPhoneContact.csv','PKG_PX_CWPHONECONTACT','TB_SRC_CWPHONECONTACT','SEGMENT',NULL,'01','01','.CWPHONECONTACT',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('CLIENTWISE_CWPostalAddress.csv','PKG_PX_CWPOSTALADDRESS','TB_SRC_CWPOSTALADDRESS','SEGMENT',NULL,'01','01','.CWPOSTALADDRESS',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('CLIENTWISE_CWSRContLinkedaccounts.csv','PKG_PX_CWSRCONTLINKEDACCOUNTS','TB_SRC_CWSRCONTLINKEDACCOUNTS','SEGMENT',NULL,'01','01','.CWSRCONTLINKEDACCOUNTS',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('CLIENTWISE_cwservicerequesthistorycoredetail.csv','PKG_PX_CWSERVICEREQUESTHISTORYCOREDETAIL','TB_SRC_CWSERVICEREQUESTHISTORYCOREDETAIL','SEGMENT',NULL,'01','01','.CWSERVICEREQUESTHISTORYCOREDETAIL',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('ASKING_PRICE.csv','PKG_PX_ASKING_PRICE','TB_SRC_ASKING_PRICE','SEGMENT',NULL,'01','01','.ASKING_PRICE',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('DEED.csv','PKG_PX_DEED','TB_SRC_DEED ','SEGMENT',NULL,'01','01','.DEED',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('NOSIA.csv','PKG_PX_NOSIA','TB_SRC_NOSIA','SEGMENT',NULL,'01','01','.NOSIA',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('NOTE.csv','PKG_PX_NOTE','TB_SRC_NOTE','SEGMENT',NULL,'01','01','.NOTE',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('OFFER.csv','PKG_PX_OFFER','TB_SRC_OFFER','SEGMENT',NULL,'01','01','.OFFER',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('PROPERTY.csv','PKG_PX_PROPERTY','TB_SRC_PROPERTY','SEGMENT',NULL,'01','01','.PROPERTY',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('RECOVERY_NOTE.csv','PKG_PX_RECOVERY_NOTE','TB_SRC_RECOVERY_NOTE','SEGMENT',NULL,'01','01','.RECOVERY_NOTE',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('SALE.csv','PKG_PX_SALE','TB_SRC_SALE','SEGMENT',NULL,'01','01','.SALE',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('SOLICITOR.csv','PKG_PX_SOLICITOR','TB_SRC_SOLICITOR','SEGMENT',NULL,'01','01','.SOLICITOR',NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('TRACE_DETAILS.csv','PKG_PX_TRACE_DETAILS','TB_SRC_TRACE_DETAILS','SEGMENT',NULL,'01','01','.TRACE_DETAILS',NULL)



--INSERTING SOURCE TARGET DEPENDENCY DETAILS INTO SDMT----
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('X02_A01' ,'PKG_UFSS_X02_A01','TB_X02_A01',NULL,NULL,' ',' ',NULL,NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('X02_A05' ,'PKG_UFSS_X02_A05','TB_X02_A05',NULL,NULL,' ',' ',NULL,NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('X02_A06' ,'PKG_UFSS_X02_A06','TB_X02_A06',NULL,NULL,' ',' ',NULL,NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('X02_A07' ,'PKG_UFSS_X02_A07','TB_X02_A07',NULL,NULL,' ',' ',NULL,NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('X02_A16' ,'PKG_UFSS_X02_A16','TB_X02_A16',NULL,NULL,' ',' ',NULL,NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('X02_C01' ,'PKG_UFSS_X02_C01','TB_X02_C01',NULL,NULL,' ',' ',NULL,NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('X02_F01' ,'PKG_UFSS_X02_F01','TB_X02_F01',NULL,NULL,' ',' ',NULL,NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('X02_GH1' ,'PKG_UFSS_X02_GH1','TB_X02_GH1',NULL,NULL,' ',' ',NULL,NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('X02_I01' ,'PKG_UFSS_X02_I01','TB_X02_I01',NULL,NULL,' ',' ',NULL,NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('X02_M01' ,'PKG_UFSS_X02_M01','TB_X02_M01',NULL,NULL,' ',' ',NULL,NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('X02_M04' ,'PKG_UFSS_X02_M04','TB_X02_M04',NULL,NULL,' ',' ',NULL,NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('X02_M06' ,'PKG_UFSS_X02_M06','TB_X02_M06',NULL,NULL,' ',' ',NULL,NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('X02_P04' ,'PKG_UFSS_X02_P04','TB_X02_P04',NULL,NULL,' ',' ',NULL,NULL)
INSERT INTO [DBO].[TB_UDMH_SDMT] VALUES('X02_S01' ,'PKG_UFSS_X02_S01','TB_X02_S01',NULL,NULL,' ',' ',NULL,NULL)


IF  EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N'[DF_TB_UDMH_LOADQUEUE_RECEIVEDDATE]') AND TYPE = 'D')
ALTER TABLE [DBO].[TB_UDMH_LOADQUEUE] DROP CONSTRAINT [DF_TB_UDMH_LOADQUEUE_RECEIVEDDATE]


IF  EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N'[DF_TB_UDMH_LOADQUEUE_RECEIVEDTIME]') AND TYPE = 'D')
ALTER TABLE [DBO].[TB_UDMH_LOADQUEUE] DROP CONSTRAINT [DF_TB_UDMH_LOADQUEUE_RECEIVEDTIME]


--LOADQUEUE CONTAINS PACKAGE INFORMATION FOR(SOURCE, TARGET, CONTROL & LOOKUP)AND STM APPLICATION PICKUP AND TRIGGER THESE PACKAGES 
IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[TB_UDMH_LOADQUEUE]') AND TYPE IN (N'U'))
DROP TABLE [DBO].[TB_UDMH_LOADQUEUE]

CREATE TABLE [DBO].[TB_UDMH_LOADQUEUE]
(
	[ID] [INT] IDENTITY(1,1) NOT NULL,
	[CHUNKNUMBER] [VARCHAR](3) NULL,
	[TRANCHENUMBER] [VARCHAR](2) NULL,
	[SOURCENAME] [VARCHAR](100) NOT NULL,
	[SSIS_PACKAGE_NAME] [VARCHAR](100) NOT NULL,
	[STAGING_TABLE_NAME] [VARCHAR](100) NOT NULL,
	[CATEGORY] [VARCHAR](30) NOT NULL,
	[PRIORITY] [NUMERIC](2, 0) NOT NULL,
	[STATUS] [VARCHAR](25) NULL,
	[RECEIVEDDATE] [DATE] NULL,
	[RECEIVEDTIME] [TIME](7) NULL,
	[MODULE_TYPE] [VARCHAR](3) NULL
)

IF NOT EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N'[DF_TB_UDMH_LOADQUEUE_RECEIVEDDATE]') AND TYPE = 'D')
ALTER TABLE [DBO].[TB_UDMH_LOADQUEUE] ADD  CONSTRAINT [DF_TB_UDMH_LOADQUEUE_RECEIVEDDATE]  DEFAULT (GETDATE()) FOR [RECEIVEDDATE]

IF NOT EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N'[DF_TB_UDMH_LOADQUEUE_RECEIVEDTIME]') AND TYPE = 'D')
ALTER TABLE [DBO].[TB_UDMH_LOADQUEUE] ADD  CONSTRAINT [DF_TB_UDMH_LOADQUEUE_RECEIVEDTIME]  DEFAULT (GETDATE()) FOR [RECEIVEDTIME]



IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[TB_UDMH_TST]') AND TYPE IN (N'U'))
DROP TABLE [DBO].[TB_UDMH_TST]

--TST TABLE CONTAINS ALL TARGET PACKAGE INFORMATION WHICH TRIGGERED BY TSA APPLICATION
CREATE TABLE [DBO].[TB_UDMH_TST]
(
	[TS_ID] [INT] IDENTITY(1,1) NOT NULL,
	[TRANCHE_NUMBER] [CHAR](2) NULL,
	[CHUNK_NUMBER] [CHAR](2) NULL,
	[TARGET_TYPE] [VARCHAR](30) NOT NULL,
	[PACKAGE_NAME] [VARCHAR](35) NOT NULL,
	[LOAD_STATUS] [VARCHAR](30) NULL,
	[EXECUTION_DATE] [DATETIME] NULL,
	[CATEGORY] [VARCHAR](30) NULL,
	[ACK_MODULENAME] [VARCHAR](70) NULL,
	[MODULE_TYPE] [VARCHAR](10) NULL,
	CONSTRAINT [PK_TB_UDMH_TST] PRIMARY KEY CLUSTERED 
	(
	[TS_ID] ASC
	)	WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]  

--INSERTING THE PRE-DATA (TARGET PACKAGES DETAILS) IN TST TABLE
SET IDENTITY_INSERT [DBO].[TB_UDMH_TST] ON
INSERT INTO [DBO].[TB_UDMH_TST] ([TS_ID], [TRANCHE_NUMBER], [CHUNK_NUMBER], [TARGET_TYPE], [PACKAGE_NAME], [LOAD_STATUS], [EXECUTION_DATE], [CATEGORY], [ACK_MODULENAME], [MODULE_TYPE]) VALUES(100,'01','01','A01','PKG_UFSS_X02_A01',NULL, NULL,'TRANSFORMATION','.AKA01.STA.X02','X02')
INSERT INTO [DBO].[TB_UDMH_TST] ([TS_ID], [TRANCHE_NUMBER], [CHUNK_NUMBER], [TARGET_TYPE], [PACKAGE_NAME], [LOAD_STATUS], [EXECUTION_DATE], [CATEGORY], [ACK_MODULENAME], [MODULE_TYPE]) VALUES(101,'01','01','A02','PKG_UFSS_X02_A02',NULL, NULL,'TRANSFORMATION','.AKA02.STA.X02','X02')
INSERT INTO [DBO].[TB_UDMH_TST] ([TS_ID], [TRANCHE_NUMBER], [CHUNK_NUMBER], [TARGET_TYPE], [PACKAGE_NAME], [LOAD_STATUS], [EXECUTION_DATE], [CATEGORY], [ACK_MODULENAME], [MODULE_TYPE]) VALUES(102,'01','01','A05','PKG_UFSS_X02_A05',NULL, NULL,'TRANSFORMATION','.AKA05.STA.X02','X02')
INSERT INTO [DBO].[TB_UDMH_TST] ([TS_ID], [TRANCHE_NUMBER], [CHUNK_NUMBER], [TARGET_TYPE], [PACKAGE_NAME], [LOAD_STATUS], [EXECUTION_DATE], [CATEGORY], [ACK_MODULENAME], [MODULE_TYPE]) VALUES(103,'01','01','A06','PKG_UFSS_X02_A06',NULL, NULL,'TRANSFORMATION','.AKA06.STA.X02','X02')
INSERT INTO [DBO].[TB_UDMH_TST] ([TS_ID], [TRANCHE_NUMBER], [CHUNK_NUMBER], [TARGET_TYPE], [PACKAGE_NAME], [LOAD_STATUS], [EXECUTION_DATE], [CATEGORY], [ACK_MODULENAME], [MODULE_TYPE]) VALUES(104,'01','01','A07','PKG_UFSS_X02_A07',NULL, NULL,'TRANSFORMATION','.AKA07.STA.X02','X02')
INSERT INTO [DBO].[TB_UDMH_TST] ([TS_ID], [TRANCHE_NUMBER], [CHUNK_NUMBER], [TARGET_TYPE], [PACKAGE_NAME], [LOAD_STATUS], [EXECUTION_DATE], [CATEGORY], [ACK_MODULENAME], [MODULE_TYPE]) VALUES(105,'01','01','A10','PKG_UFSS_X02_A10',NULL, NULL,'TRANSFORMATION','.AKA10.STA.X02','X02')
INSERT INTO [DBO].[TB_UDMH_TST] ([TS_ID], [TRANCHE_NUMBER], [CHUNK_NUMBER], [TARGET_TYPE], [PACKAGE_NAME], [LOAD_STATUS], [EXECUTION_DATE], [CATEGORY], [ACK_MODULENAME], [MODULE_TYPE]) VALUES(106,'01','01','A16','PKG_UFSS_X02_A16',NULL, NULL,'TRANSFORMATION','.AKA16.STA.X02','X02')
INSERT INTO [DBO].[TB_UDMH_TST] ([TS_ID], [TRANCHE_NUMBER], [CHUNK_NUMBER], [TARGET_TYPE], [PACKAGE_NAME], [LOAD_STATUS], [EXECUTION_DATE], [CATEGORY], [ACK_MODULENAME], [MODULE_TYPE]) VALUES(107,'01','01','C01','PKG_UFSS_X02_C01',NULL, NULL,'TRANSFORMATION','.AKC01.STA.X02','X02')
INSERT INTO [DBO].[TB_UDMH_TST] ([TS_ID], [TRANCHE_NUMBER], [CHUNK_NUMBER], [TARGET_TYPE], [PACKAGE_NAME], [LOAD_STATUS], [EXECUTION_DATE], [CATEGORY], [ACK_MODULENAME], [MODULE_TYPE]) VALUES(108,'01','01','C02','PKG_UFSS_X02_C02',NULL, NULL,'TRANSFORMATION','.AKC02.STA.X02','X02')
INSERT INTO [DBO].[TB_UDMH_TST] ([TS_ID], [TRANCHE_NUMBER], [CHUNK_NUMBER], [TARGET_TYPE], [PACKAGE_NAME], [LOAD_STATUS], [EXECUTION_DATE], [CATEGORY], [ACK_MODULENAME], [MODULE_TYPE]) VALUES(109,'01','01','C03','PKG_UFSS_X02_C03',NULL, NULL,'TRANSFORMATION','.AKC03.STA.X02','X02')
INSERT INTO [DBO].[TB_UDMH_TST] ([TS_ID], [TRANCHE_NUMBER], [CHUNK_NUMBER], [TARGET_TYPE], [PACKAGE_NAME], [LOAD_STATUS], [EXECUTION_DATE], [CATEGORY], [ACK_MODULENAME], [MODULE_TYPE]) VALUES(110,'01','01','F01','PKG_UFSS_X02_F01',NULL, NULL,'TRANSFORMATION','.AKF01.STA.X02','X02')
--INSERT INTO [DBO].[TB_UDMH_TST] ([TS_ID], [TRANCHE_NUMBER], [CHUNK_NUMBER], [TARGET_TYPE], [PACKAGE_NAME], [LOAD_STATUS], [EXECUTION_DATE], [CATEGORY], [ACK_MODULENAME], [MODULE_TYPE]) VALUES(111,'01','01','F03','PKG_UFSS_X02_F03',NULL, NULL,'TRANSFORMATION','.AKF03.STA.X02','X02')
INSERT INTO [DBO].[TB_UDMH_TST] ([TS_ID], [TRANCHE_NUMBER], [CHUNK_NUMBER], [TARGET_TYPE], [PACKAGE_NAME], [LOAD_STATUS], [EXECUTION_DATE], [CATEGORY], [ACK_MODULENAME], [MODULE_TYPE]) VALUES(112,'01','01','F05','PKG_UFSS_X02_F05',NULL, NULL,'TRANSFORMATION','.AKF05.STA.X02','X02')
INSERT INTO [DBO].[TB_UDMH_TST] ([TS_ID], [TRANCHE_NUMBER], [CHUNK_NUMBER], [TARGET_TYPE], [PACKAGE_NAME], [LOAD_STATUS], [EXECUTION_DATE], [CATEGORY], [ACK_MODULENAME], [MODULE_TYPE]) VALUES(113,'01','01','FH1','PKG_UFSS_X02_FH1',NULL, NULL,'TRANSFORMATION','.AKFH1.STA.X02','X02')
INSERT INTO [DBO].[TB_UDMH_TST] ([TS_ID], [TRANCHE_NUMBER], [CHUNK_NUMBER], [TARGET_TYPE], [PACKAGE_NAME], [LOAD_STATUS], [EXECUTION_DATE], [CATEGORY], [ACK_MODULENAME], [MODULE_TYPE]) VALUES(114,'01','01','FT1','PKG_UFSS_X02_FT1',NULL, NULL,'TRANSFORMATION','.AKFT1.STA.X02','X02')
INSERT INTO [DBO].[TB_UDMH_TST] ([TS_ID], [TRANCHE_NUMBER], [CHUNK_NUMBER], [TARGET_TYPE], [PACKAGE_NAME], [LOAD_STATUS], [EXECUTION_DATE], [CATEGORY], [ACK_MODULENAME], [MODULE_TYPE]) VALUES(115,'01','01','GH1','PKG_UFSS_X02_GH1',NULL, NULL,'TRANSFORMATION','.AKGH1.STA.X02','X02')
INSERT INTO [DBO].[TB_UDMH_TST] ([TS_ID], [TRANCHE_NUMBER], [CHUNK_NUMBER], [TARGET_TYPE], [PACKAGE_NAME], [LOAD_STATUS], [EXECUTION_DATE], [CATEGORY], [ACK_MODULENAME], [MODULE_TYPE]) VALUES(116,'01','01','GT1','PKG_UFSS_X02_GT1',NULL, NULL,'TRANSFORMATION','.AKGT1.STA.X02','X02')
INSERT INTO [DBO].[TB_UDMH_TST] ([TS_ID], [TRANCHE_NUMBER], [CHUNK_NUMBER], [TARGET_TYPE], [PACKAGE_NAME], [LOAD_STATUS], [EXECUTION_DATE], [CATEGORY], [ACK_MODULENAME], [MODULE_TYPE]) VALUES(117,'01','01','I01','PKG_UFSS_X02_I01',NULL, NULL,'TRANSFORMATION','.AKI01.STA.X02','X02')
INSERT INTO [DBO].[TB_UDMH_TST] ([TS_ID], [TRANCHE_NUMBER], [CHUNK_NUMBER], [TARGET_TYPE], [PACKAGE_NAME], [LOAD_STATUS], [EXECUTION_DATE], [CATEGORY], [ACK_MODULENAME], [MODULE_TYPE]) VALUES(118,'01','01','I02','PKG_UFSS_X02_I02',NULL, NULL,'TRANSFORMATION','.AKI02.STA.X02','X02')
INSERT INTO [DBO].[TB_UDMH_TST] ([TS_ID], [TRANCHE_NUMBER], [CHUNK_NUMBER], [TARGET_TYPE], [PACKAGE_NAME], [LOAD_STATUS], [EXECUTION_DATE], [CATEGORY], [ACK_MODULENAME], [MODULE_TYPE]) VALUES(119,'01','01','M01','PKG_UFSS_X02_M01',NULL, NULL,'TRANSFORMATION','.AKM01.STA.X02','X02')
INSERT INTO [DBO].[TB_UDMH_TST] ([TS_ID], [TRANCHE_NUMBER], [CHUNK_NUMBER], [TARGET_TYPE], [PACKAGE_NAME], [LOAD_STATUS], [EXECUTION_DATE], [CATEGORY], [ACK_MODULENAME], [MODULE_TYPE]) VALUES(120,'01','01','M02','PKG_UFSS_X02_M02',NULL, NULL,'TRANSFORMATION','.AKM02.STA.X02','X02')
INSERT INTO [DBO].[TB_UDMH_TST] ([TS_ID], [TRANCHE_NUMBER], [CHUNK_NUMBER], [TARGET_TYPE], [PACKAGE_NAME], [LOAD_STATUS], [EXECUTION_DATE], [CATEGORY], [ACK_MODULENAME], [MODULE_TYPE]) VALUES(121,'01','01','M04','PKG_UFSS_X02_M04',NULL, NULL,'TRANSFORMATION','.AKM04.STA.X02','X02')
INSERT INTO [DBO].[TB_UDMH_TST] ([TS_ID], [TRANCHE_NUMBER], [CHUNK_NUMBER], [TARGET_TYPE], [PACKAGE_NAME], [LOAD_STATUS], [EXECUTION_DATE], [CATEGORY], [ACK_MODULENAME], [MODULE_TYPE]) VALUES(122,'01','01','M05','PKG_UFSS_X02_M05',NULL, NULL,'TRANSFORMATION','.AKM05.STA.X02','X02')
INSERT INTO [DBO].[TB_UDMH_TST] ([TS_ID], [TRANCHE_NUMBER], [CHUNK_NUMBER], [TARGET_TYPE], [PACKAGE_NAME], [LOAD_STATUS], [EXECUTION_DATE], [CATEGORY], [ACK_MODULENAME], [MODULE_TYPE]) VALUES(123,'01','01','M06','PKG_UFSS_X02_M06',NULL, NULL,'TRANSFORMATION','.AKM06.STA.X02','X02')
INSERT INTO [DBO].[TB_UDMH_TST] ([TS_ID], [TRANCHE_NUMBER], [CHUNK_NUMBER], [TARGET_TYPE], [PACKAGE_NAME], [LOAD_STATUS], [EXECUTION_DATE], [CATEGORY], [ACK_MODULENAME], [MODULE_TYPE]) VALUES(124,'01','01','M07','PKG_UFSS_X02_M07',NULL, NULL,'TRANSFORMATION','.AKM07.STA.X02','X02')
INSERT INTO [DBO].[TB_UDMH_TST] ([TS_ID], [TRANCHE_NUMBER], [CHUNK_NUMBER], [TARGET_TYPE], [PACKAGE_NAME], [LOAD_STATUS], [EXECUTION_DATE], [CATEGORY], [ACK_MODULENAME], [MODULE_TYPE]) VALUES(125,'01','01','M09','PKG_UFSS_X02_M09',NULL, NULL,'TRANSFORMATION','.AKM09.STA.X02','X02')
INSERT INTO [DBO].[TB_UDMH_TST] ([TS_ID], [TRANCHE_NUMBER], [CHUNK_NUMBER], [TARGET_TYPE], [PACKAGE_NAME], [LOAD_STATUS], [EXECUTION_DATE], [CATEGORY], [ACK_MODULENAME], [MODULE_TYPE]) VALUES(126,'01','01','M10','PKG_UFSS_X02_M10',NULL, NULL,'TRANSFORMATION','.AKM10.STA.X02','X02')
INSERT INTO [DBO].[TB_UDMH_TST] ([TS_ID], [TRANCHE_NUMBER], [CHUNK_NUMBER], [TARGET_TYPE], [PACKAGE_NAME], [LOAD_STATUS], [EXECUTION_DATE], [CATEGORY], [ACK_MODULENAME], [MODULE_TYPE]) VALUES(127,'01','01','M11','PKG_UFSS_X02_M11',NULL, NULL,'TRANSFORMATION','.AKM11.STA.X02','X02')
INSERT INTO [DBO].[TB_UDMH_TST] ([TS_ID], [TRANCHE_NUMBER], [CHUNK_NUMBER], [TARGET_TYPE], [PACKAGE_NAME], [LOAD_STATUS], [EXECUTION_DATE], [CATEGORY], [ACK_MODULENAME], [MODULE_TYPE]) VALUES(128,'01','01','M13','PKG_UFSS_X02_M13',NULL, NULL,'TRANSFORMATION','.AKM13.STA.X02','X02')
INSERT INTO [DBO].[TB_UDMH_TST] ([TS_ID], [TRANCHE_NUMBER], [CHUNK_NUMBER], [TARGET_TYPE], [PACKAGE_NAME], [LOAD_STATUS], [EXECUTION_DATE], [CATEGORY], [ACK_MODULENAME], [MODULE_TYPE]) VALUES(129,'01','01','M14','PKG_UFSS_X02_M14',NULL, NULL,'TRANSFORMATION','.AKM14.STA.X02','X02')
INSERT INTO [DBO].[TB_UDMH_TST] ([TS_ID], [TRANCHE_NUMBER], [CHUNK_NUMBER], [TARGET_TYPE], [PACKAGE_NAME], [LOAD_STATUS], [EXECUTION_DATE], [CATEGORY], [ACK_MODULENAME], [MODULE_TYPE]) VALUES(130,'01','01','M18','PKG_UFSS_X02_M18',NULL, NULL,'TRANSFORMATION','.AKM18.STA.X02','X02')
INSERT INTO [DBO].[TB_UDMH_TST] ([TS_ID], [TRANCHE_NUMBER], [CHUNK_NUMBER], [TARGET_TYPE], [PACKAGE_NAME], [LOAD_STATUS], [EXECUTION_DATE], [CATEGORY], [ACK_MODULENAME], [MODULE_TYPE]) VALUES(131,'01','01','MA5','PKG_UFSS_X02_MA5',NULL, NULL,'TRANSFORMATION','.AKMA5.STA.X02','X02')
INSERT INTO [DBO].[TB_UDMH_TST] ([TS_ID], [TRANCHE_NUMBER], [CHUNK_NUMBER], [TARGET_TYPE], [PACKAGE_NAME], [LOAD_STATUS], [EXECUTION_DATE], [CATEGORY], [ACK_MODULENAME], [MODULE_TYPE]) VALUES(132,'01','01','MA6','PKG_UFSS_X02_MA6',NULL, NULL,'TRANSFORMATION','.AKMA6.STA.X02','X02')
INSERT INTO [DBO].[TB_UDMH_TST] ([TS_ID], [TRANCHE_NUMBER], [CHUNK_NUMBER], [TARGET_TYPE], [PACKAGE_NAME], [LOAD_STATUS], [EXECUTION_DATE], [CATEGORY], [ACK_MODULENAME], [MODULE_TYPE]) VALUES(133,'01','01','P01','PKG_UFSS_X02_P01',NULL, NULL,'TRANSFORMATION','.AKP01.STA.X02','X02')
INSERT INTO [DBO].[TB_UDMH_TST] ([TS_ID], [TRANCHE_NUMBER], [CHUNK_NUMBER], [TARGET_TYPE], [PACKAGE_NAME], [LOAD_STATUS], [EXECUTION_DATE], [CATEGORY], [ACK_MODULENAME], [MODULE_TYPE]) VALUES(134,'01','01','P03','PKG_UFSS_X02_P03',NULL, NULL,'TRANSFORMATION','.AKP03.STA.X02','X02')
INSERT INTO [DBO].[TB_UDMH_TST] ([TS_ID], [TRANCHE_NUMBER], [CHUNK_NUMBER], [TARGET_TYPE], [PACKAGE_NAME], [LOAD_STATUS], [EXECUTION_DATE], [CATEGORY], [ACK_MODULENAME], [MODULE_TYPE]) VALUES(135,'01','01','P04','PKG_UFSS_X02_P04',NULL, NULL,'TRANSFORMATION','.AKP04.STA.X02','X02')
INSERT INTO [DBO].[TB_UDMH_TST] ([TS_ID], [TRANCHE_NUMBER], [CHUNK_NUMBER], [TARGET_TYPE], [PACKAGE_NAME], [LOAD_STATUS], [EXECUTION_DATE], [CATEGORY], [ACK_MODULENAME], [MODULE_TYPE]) VALUES(136,'01','01','S01','PKG_UFSS_X02_S01',NULL, NULL,'TRANSFORMATION','.AKS01.STA.X02','X02')
INSERT INTO [DBO].[TB_UDMH_TST] ([TS_ID], [TRANCHE_NUMBER], [CHUNK_NUMBER], [TARGET_TYPE], [PACKAGE_NAME], [LOAD_STATUS], [EXECUTION_DATE], [CATEGORY], [ACK_MODULENAME], [MODULE_TYPE]) VALUES(137,'01','01','S02','PKG_UFSS_X02_S02',NULL, NULL,'TRANSFORMATION','.AKS02.STA.X02','X02')
INSERT INTO [DBO].[TB_UDMH_TST] ([TS_ID], [TRANCHE_NUMBER], [CHUNK_NUMBER], [TARGET_TYPE], [PACKAGE_NAME], [LOAD_STATUS], [EXECUTION_DATE], [CATEGORY], [ACK_MODULENAME], [MODULE_TYPE]) VALUES(138,'01','01','S03','PKG_UFSS_X02_S03',NULL, NULL,'TRANSFORMATION','.AKS03.STA.X02','X02')

--X02 PACKAGE
INSERT INTO [DBO].[TB_UDMH_TST] ([TS_ID], [TRANCHE_NUMBER], [CHUNK_NUMBER], [TARGET_TYPE], [PACKAGE_NAME], [LOAD_STATUS], [EXECUTION_DATE], [CATEGORY], [ACK_MODULENAME], [MODULE_TYPE]) VALUES( 139, '01', '01', 'X02','PKG_UFSS_X02', NULL, NULL, 'GENERATE', '.AKX02G.STA.X02', 'X02')
	
SET IDENTITY_INSERT [DBO].[TB_UDMH_TST] OFF;


--CTL TABLE CONTAINS ALL CONTROL FILE INFOMATION  
IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[TB_UDMH_CTL]') AND TYPE IN (N'U'))
DROP TABLE [DBO].[TB_UDMH_CTL]

CREATE TABLE [DBO].[TB_UDMH_CTL]
(
  ALL_RUNTAG VARCHAR(4) NULL,
  WS_MIGR_DATE DATE NULL,
  EVENT_RUN_NO INT NULL,
  CURRENT_FLAG VARCHAR(8) NULL,
  WS_ACK_FILEPATH VARCHAR(255) NULL,
  WS_BASE_ACK_FILENAME VARCHAR(255) NULL,
  SOURCE CHAR(5) NULL,
  GRACEDAYS INT NULL,  
  FUNDER_CODE CHAR(3) NULL,
  BOOK_NUMBER INT NULL,

)  

ALTER TABLE [DBO].[TB_UDMH_CTL] ADD  CONSTRAINT [DF_TB_UDMH_CTL_RUN_NUM]  DEFAULT ((1)) FOR [EVENT_RUN_NO]

--CTL_TEMP TABLE CONTAINS ALL THE INFORARMATION ABOUT CONTROL FILE/PACKAGES
IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[TB_UDMH_CTL_TEMP]') AND TYPE IN (N'U'))
DROP TABLE [DBO].[TB_UDMH_CTL_TEMP]

CREATE TABLE [DBO].[TB_UDMH_CTL_TEMP](
   ALL_RUNTAG VARCHAR(4) NULL,
  WS_MIGR_DATE VARCHAR(10) NULL,
  ACK_FILEPATH VARCHAR(100) NULL,
  BASE_ACK_FN VARCHAR(40) NULL,
  AUTOMATION_SWITCH VARCHAR(10) NULL,
  FLOW1_SEGCNT VARCHAR(3) NULL,
  CTRL_SOURCE VARCHAR(5) NULL,
  GRACEDAYS VARCHAR(10) NULL,
  FUNDER_CODE VARCHAR(3) NULL,
  BOOK_NUMBER VARCHAR(3) NULL,
  WS_BASE_ACK_FILENAME VARCHAR(255) NULL,
  WS_BATCHFILEPATH VARCHAR(255) NULL,

) ON [PRIMARY]



IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[TB_UDMH_SRCTGT_DEP]') AND TYPE IN (N'U'))
DROP TABLE [DBO].[TB_UDMH_SRCTGT_DEP]

CREATE TABLE [DBO].[TB_UDMH_SRCTGT_DEP]
(
	[DS_ID] [INT] IDENTITY(1,1) NOT NULL,
	[TARGET_TYPE] [VARCHAR](30) NOT NULL,
	[DEPENDENT_SOURCE] [CHAR](50) NOT NULL,
	[STAGING_TABLE_NAME] [VARCHAR](35) NOT NULL,
	CONSTRAINT [PK_TB_UDMH_SRCTGT_DEP] PRIMARY KEY CLUSTERED 
	(
	[TARGET_TYPE] ASC,
	[DEPENDENT_SOURCE] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
)	ON [PRIMARY]
 
--INSERTING THE PRE-DATA IN SRCTGT_DEP TABLE
SET IDENTITY_INSERT [DBO].[TB_UDMH_SRCTGT_DEP] ON
   INSERT [DBO].[TB_UDMH_SRCTGT_DEP] ([DS_ID], [TARGET_TYPE], [DEPENDENT_SOURCE], [STAGING_TABLE_NAME]) VALUES (100, 'A02', 'X02_A07', 'TB_X02_A02')
   INSERT [DBO].[TB_UDMH_SRCTGT_DEP] ([DS_ID], [TARGET_TYPE], [DEPENDENT_SOURCE], [STAGING_TABLE_NAME]) VALUES (101, 'A05', 'X02_A06', 'TB_X02_A05')
   INSERT [DBO].[TB_UDMH_SRCTGT_DEP] ([DS_ID], [TARGET_TYPE], [DEPENDENT_SOURCE], [STAGING_TABLE_NAME]) VALUES (102, 'A05', 'X02_GH1', 'TB_X02_A05')
   INSERT [DBO].[TB_UDMH_SRCTGT_DEP] ([DS_ID], [TARGET_TYPE], [DEPENDENT_SOURCE], [STAGING_TABLE_NAME]) VALUES (103, 'A06', 'X02_A01', 'TB_X02_A06')
   INSERT [DBO].[TB_UDMH_SRCTGT_DEP] ([DS_ID], [TARGET_TYPE], [DEPENDENT_SOURCE], [STAGING_TABLE_NAME]) VALUES (104, 'A07', 'X02_A05', 'TB_X02_A07')
   INSERT [DBO].[TB_UDMH_SRCTGT_DEP] ([DS_ID], [TARGET_TYPE], [DEPENDENT_SOURCE], [STAGING_TABLE_NAME]) VALUES (105, 'A16', 'X02_A06', 'TB_X02_A16')
   INSERT [DBO].[TB_UDMH_SRCTGT_DEP] ([DS_ID], [TARGET_TYPE], [DEPENDENT_SOURCE], [STAGING_TABLE_NAME]) VALUES (106, 'A16', 'X02_M01', 'TB_X02_A16')
   INSERT [DBO].[TB_UDMH_SRCTGT_DEP] ([DS_ID], [TARGET_TYPE], [DEPENDENT_SOURCE], [STAGING_TABLE_NAME]) VALUES (107, 'C03', 'X02_C01', 'TB_X02_C03')
   INSERT [DBO].[TB_UDMH_SRCTGT_DEP] ([DS_ID], [TARGET_TYPE], [DEPENDENT_SOURCE], [STAGING_TABLE_NAME]) VALUES (108, 'F01', 'X02_A01', 'TB_X02_F01')
   INSERT [DBO].[TB_UDMH_SRCTGT_DEP] ([DS_ID], [TARGET_TYPE], [DEPENDENT_SOURCE], [STAGING_TABLE_NAME]) VALUES (109, 'GH1', 'X02_C01', 'TB_X02_GH1')
   INSERT [DBO].[TB_UDMH_SRCTGT_DEP] ([DS_ID], [TARGET_TYPE], [DEPENDENT_SOURCE], [STAGING_TABLE_NAME]) VALUES (110, 'I02', 'X02_I01', 'TB_X02_I02')
   INSERT [DBO].[TB_UDMH_SRCTGT_DEP] ([DS_ID], [TARGET_TYPE], [DEPENDENT_SOURCE], [STAGING_TABLE_NAME]) VALUES (111, 'M01', 'X02_C01', 'TB_X02_M01')
   INSERT [DBO].[TB_UDMH_SRCTGT_DEP] ([DS_ID], [TARGET_TYPE], [DEPENDENT_SOURCE], [STAGING_TABLE_NAME]) VALUES (112, 'M01', 'X02_S01', 'TB_X02_M01')
   INSERT [DBO].[TB_UDMH_SRCTGT_DEP] ([DS_ID], [TARGET_TYPE], [DEPENDENT_SOURCE], [STAGING_TABLE_NAME]) VALUES (113, 'M07', 'X02_GH1', 'TB_X02_M07')
   INSERT [DBO].[TB_UDMH_SRCTGT_DEP] ([DS_ID], [TARGET_TYPE], [DEPENDENT_SOURCE], [STAGING_TABLE_NAME]) VALUES (114, 'M09', 'X02_A07', 'TB_X02_M09')
   INSERT [DBO].[TB_UDMH_SRCTGT_DEP] ([DS_ID], [TARGET_TYPE], [DEPENDENT_SOURCE], [STAGING_TABLE_NAME]) VALUES (115, 'M09', 'X02_A16', 'TB_X02_M09')
   INSERT [DBO].[TB_UDMH_SRCTGT_DEP] ([DS_ID], [TARGET_TYPE], [DEPENDENT_SOURCE], [STAGING_TABLE_NAME]) VALUES (116, 'M09', 'X02_M01', 'TB_X02_M09')
   INSERT [DBO].[TB_UDMH_SRCTGT_DEP] ([DS_ID], [TARGET_TYPE], [DEPENDENT_SOURCE], [STAGING_TABLE_NAME]) VALUES (117, 'M09', 'X02_M04', 'TB_X02_M09')
   INSERT [DBO].[TB_UDMH_SRCTGT_DEP] ([DS_ID], [TARGET_TYPE], [DEPENDENT_SOURCE], [STAGING_TABLE_NAME]) VALUES (118, 'M10', 'X02_A05', 'TB_X02_M10')
   INSERT [DBO].[TB_UDMH_SRCTGT_DEP] ([DS_ID], [TARGET_TYPE], [DEPENDENT_SOURCE], [STAGING_TABLE_NAME]) VALUES (119, 'MA6', 'X02_F01', 'TB_X02_MA6')
   INSERT [DBO].[TB_UDMH_SRCTGT_DEP] ([DS_ID], [TARGET_TYPE], [DEPENDENT_SOURCE], [STAGING_TABLE_NAME]) VALUES (120, 'MA6', 'X02_M06', 'TB_X02_MA6')
   INSERT [DBO].[TB_UDMH_SRCTGT_DEP] ([DS_ID], [TARGET_TYPE], [DEPENDENT_SOURCE], [STAGING_TABLE_NAME]) VALUES (121, 'P01', 'X02_A16', 'TB_X02_P01')
   INSERT [DBO].[TB_UDMH_SRCTGT_DEP] ([DS_ID], [TARGET_TYPE], [DEPENDENT_SOURCE], [STAGING_TABLE_NAME]) VALUES (122, 'P03', 'X02_P04', 'TB_X02_P03')
   INSERT [DBO].[TB_UDMH_SRCTGT_DEP] ([DS_ID], [TARGET_TYPE], [DEPENDENT_SOURCE], [STAGING_TABLE_NAME]) VALUES (123, 'S01', 'X02_P04', 'TB_X02_S01')
   
SET IDENTITY_INSERT [DBO].[TB_UDMH_SRCTGT_DEP] OFF;



IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[TB_UDMH_AUDIT]') AND TYPE IN (N'U'))
DROP TABLE [DBO].[TB_UDMH_AUDIT]

CREATE TABLE [DBO].[TB_UDMH_AUDIT]
(
	[LOG_ID] [INT] IDENTITY(1,1) NOT NULL,
	[LOG_DATETIME] [DATETIME] NULL,
	[LOG_COMPONENT] [VARCHAR](50) NULL,
	[LOG_MESSAGE] [VARCHAR](MAX) NULL
)


IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[TB_UDMH_LOOKUP_STATUS]') AND TYPE IN (N'U'))
DROP TABLE [DBO].[TB_UDMH_LOOKUP_STATUS]

CREATE TABLE [DBO].[TB_UDMH_LOOKUP_STATUS](
	[PACKAGE_NAME] [VARCHAR](35) NOT NULL,
	[SOURCE_TABLE_NAME] [VARCHAR](35) NOT NULL,
	[FILE_VERSION] [CHAR](5) NULL,
	[FILE_STATUS] [CHAR](25) NULL
	CONSTRAINT [PK_TB_UDMH_LOOKUP_STATUS] PRIMARY KEY CLUSTERED 
	(
	[PACKAGE_NAME] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

--INSERTING THE PRE-DATA IN LOOKUP_STATUS TABLE
INSERT [DBO].[TB_UDMH_LOOKUP_STATUS] (  [PACKAGE_NAME], [SOURCE_TABLE_NAME],[FILE_VERSION],[FILE_STATUS]) VALUES (N'PKG_XFM_LUT_ARRNG_REAS',N'TB_XFM_LUT_ARRNG_REAS',NULL, NULL)
INSERT [DBO].[TB_UDMH_LOOKUP_STATUS] (  [PACKAGE_NAME], [SOURCE_TABLE_NAME],[FILE_VERSION],[FILE_STATUS]) VALUES (N'PKG_XFM_LUT_BACS',N'TB_XFM_LUT_BACS',NULL, NULL)
INSERT [DBO].[TB_UDMH_LOOKUP_STATUS] (  [PACKAGE_NAME], [SOURCE_TABLE_NAME],[FILE_VERSION],[FILE_STATUS]) VALUES (N'PKG_XFM_LUT_BOOK_FUNDER',N'TB_XFM_LUT_BOOK_FUNDER',NULL, NULL)
INSERT [DBO].[TB_UDMH_LOOKUP_STATUS] (  [PACKAGE_NAME], [SOURCE_TABLE_NAME],[FILE_VERSION],[FILE_STATUS]) VALUES (N'PKG_XFM_LUT_BRANCH',N'TB_XFM_LUT_BRANCH',NULL, NULL)
INSERT [DBO].[TB_UDMH_LOOKUP_STATUS] (  [PACKAGE_NAME], [SOURCE_TABLE_NAME],[FILE_VERSION],[FILE_STATUS]) VALUES (N'PKG_XFM_LUT_CNTRY_CDE',N'TB_XFM_LUT_CNTRY_CDE',NULL, NULL)
INSERT [DBO].[TB_UDMH_LOOKUP_STATUS] (  [PACKAGE_NAME], [SOURCE_TABLE_NAME],[FILE_VERSION],[FILE_STATUS]) VALUES (N'PKG_XFM_LUT_DEED_REAS',N'TB_XFM_LUT_DEED_REAS',NULL, NULL)
INSERT [DBO].[TB_UDMH_LOOKUP_STATUS] (  [PACKAGE_NAME], [SOURCE_TABLE_NAME],[FILE_VERSION],[FILE_STATUS]) VALUES (N'PKG_XFM_LUT_EMPST',N'TB_XFM_LUT_EMPST',NULL, NULL)
INSERT [DBO].[TB_UDMH_LOOKUP_STATUS] (  [PACKAGE_NAME], [SOURCE_TABLE_NAME],[FILE_VERSION],[FILE_STATUS]) VALUES (N'PKG_XFM_LUT_FRQPAD',N'TB_XFM_LUT_FRQPAD',NULL, NULL)
INSERT [DBO].[TB_UDMH_LOOKUP_STATUS] (  [PACKAGE_NAME], [SOURCE_TABLE_NAME],[FILE_VERSION],[FILE_STATUS]) VALUES (N'PKG_XFM_LUT_FUNDS_METHOD',N'TB_XFM_LUT_FUNDS_METHOD',NULL, NULL)
INSERT [DBO].[TB_UDMH_LOOKUP_STATUS] (  [PACKAGE_NAME], [SOURCE_TABLE_NAME],[FILE_VERSION],[FILE_STATUS]) VALUES (N'PKG_XFM_LUT_HISTORIC_ACNO',N'TB_XFM_LUT_HISTORIC_ACNO',NULL, NULL)
INSERT [DBO].[TB_UDMH_LOOKUP_STATUS] (  [PACKAGE_NAME], [SOURCE_TABLE_NAME],[FILE_VERSION],[FILE_STATUS]) VALUES (N'PKG_XFM_LUT_INSURANCE_CONDITION',N'TB_XFM_LUT_INSURANCE_CONDITION',NULL, NULL)
INSERT [DBO].[TB_UDMH_LOOKUP_STATUS] (  [PACKAGE_NAME], [SOURCE_TABLE_NAME],[FILE_VERSION],[FILE_STATUS]) VALUES (N'PKG_XFM_LUT_INSURANCE_ITEM',N'TB_XFM_LUT_INSURANCE_ITEM',NULL, NULL)
INSERT [DBO].[TB_UDMH_LOOKUP_STATUS] (  [PACKAGE_NAME], [SOURCE_TABLE_NAME],[FILE_VERSION],[FILE_STATUS]) VALUES (N'PKG_XFM_LUT_INSURANCE_PRODUCT',N'TB_XFM_LUT_INSURANCE_PRODUCT',NULL, NULL)
INSERT [DBO].[TB_UDMH_LOOKUP_STATUS] (  [PACKAGE_NAME], [SOURCE_TABLE_NAME],[FILE_VERSION],[FILE_STATUS]) VALUES (N'PKG_XFM_LUT_M_STATUS',N'TB_XFM_LUT_M_STATUS',NULL, NULL)
INSERT [DBO].[TB_UDMH_LOOKUP_STATUS] (  [PACKAGE_NAME], [SOURCE_TABLE_NAME],[FILE_VERSION],[FILE_STATUS]) VALUES (N'PKG_XFM_LUT_MARKETING_CHANNEL',N'TB_XFM_LUT_MARKETING_CHANNEL',NULL, NULL)
INSERT [DBO].[TB_UDMH_LOOKUP_STATUS] (  [PACKAGE_NAME], [SOURCE_TABLE_NAME],[FILE_VERSION],[FILE_STATUS]) VALUES (N'PKG_XFM_LUT_MEDIACODE',N'TB_XFM_LUT_MEDIACODE',NULL, NULL)
INSERT [DBO].[TB_UDMH_LOOKUP_STATUS] (  [PACKAGE_NAME], [SOURCE_TABLE_NAME],[FILE_VERSION],[FILE_STATUS]) VALUES (N'PKG_XFM_LUT_MISC',N'TB_XFM_LUT_MISC',NULL, NULL)
INSERT [DBO].[TB_UDMH_LOOKUP_STATUS] (  [PACKAGE_NAME], [SOURCE_TABLE_NAME],[FILE_VERSION],[FILE_STATUS]) VALUES (N'PKG_XFM_LUT_MORTGAGE_REVIEW',N'TB_XFM_LUT_MORTGAGE_REVIEW',NULL, NULL)
INSERT [DBO].[TB_UDMH_LOOKUP_STATUS] (  [PACKAGE_NAME], [SOURCE_TABLE_NAME],[FILE_VERSION],[FILE_STATUS]) VALUES (N'PKG_XFM_LUT_MR_ETC',N'TB_XFM_LUT_MR_ETC',NULL, NULL)
INSERT [DBO].[TB_UDMH_LOOKUP_STATUS] (  [PACKAGE_NAME], [SOURCE_TABLE_NAME],[FILE_VERSION],[FILE_STATUS]) VALUES (N'PKG_XFM_LUT_NATIONLTY',N'TB_XFM_LUT_NATIONLTY',NULL, NULL)
INSERT [DBO].[TB_UDMH_LOOKUP_STATUS] (  [PACKAGE_NAME], [SOURCE_TABLE_NAME],[FILE_VERSION],[FILE_STATUS]) VALUES (N'PKG_XFM_LUT_NM_SUFFIX',N'TB_XFM_LUT_NM_SUFFIX',NULL, NULL)
INSERT [DBO].[TB_UDMH_LOOKUP_STATUS] (  [PACKAGE_NAME], [SOURCE_TABLE_NAME],[FILE_VERSION],[FILE_STATUS]) VALUES (N'PKG_XFM_LUT_NOTETYPE',N'TB_XFM_LUT_NOTETYPE',NULL, NULL)
INSERT [DBO].[TB_UDMH_LOOKUP_STATUS] (  [PACKAGE_NAME], [SOURCE_TABLE_NAME],[FILE_VERSION],[FILE_STATUS]) VALUES (N'PKG_XFM_LUT_OCCUPATION',N'TB_XFM_LUT_OCCUPATION',NULL, NULL)
INSERT [DBO].[TB_UDMH_LOOKUP_STATUS] (  [PACKAGE_NAME], [SOURCE_TABLE_NAME],[FILE_VERSION],[FILE_STATUS]) VALUES (N'PKG_XFM_LUT_OFFER_STATUS',N'TB_XFM_LUT_OFFER_STATUS',NULL, NULL)
INSERT [DBO].[TB_UDMH_LOOKUP_STATUS] (  [PACKAGE_NAME], [SOURCE_TABLE_NAME],[FILE_VERSION],[FILE_STATUS]) VALUES (N'PKG_XFM_LUT_PENDING_RATECHANGE',N'TB_XFM_LUT_PENDING_RATECHANGE',NULL, NULL)
INSERT [DBO].[TB_UDMH_LOOKUP_STATUS] (  [PACKAGE_NAME], [SOURCE_TABLE_NAME],[FILE_VERSION],[FILE_STATUS]) VALUES (N'PKG_XFM_LUT_PRODUCT',N'TB_XFM_LUT_PRODUCT',NULL, NULL)
INSERT [DBO].[TB_UDMH_LOOKUP_STATUS] (  [PACKAGE_NAME], [SOURCE_TABLE_NAME],[FILE_VERSION],[FILE_STATUS]) VALUES (N'PKG_XFM_LUT_PROP_WARANTY',N'TB_XFM_LUT_PROP_WARANTY',NULL, NULL)
INSERT [DBO].[TB_UDMH_LOOKUP_STATUS] (  [PACKAGE_NAME], [SOURCE_TABLE_NAME],[FILE_VERSION],[FILE_STATUS]) VALUES (N'PKG_XFM_LUT_PURPOSE',N'TB_XFM_LUT_PURPOSE',NULL, NULL)
INSERT [DBO].[TB_UDMH_LOOKUP_STATUS] (  [PACKAGE_NAME], [SOURCE_TABLE_NAME],[FILE_VERSION],[FILE_STATUS]) VALUES (N'PKG_XFM_LUT_RELATIONS',N'TB_XFM_LUT_RELATIONS',NULL, NULL)
INSERT [DBO].[TB_UDMH_LOOKUP_STATUS] (  [PACKAGE_NAME], [SOURCE_TABLE_NAME],[FILE_VERSION],[FILE_STATUS]) VALUES (N'PKG_XFM_LUT_REPO_METHOD',N'TB_XFM_LUT_REPO_METHOD',NULL, NULL)
INSERT [DBO].[TB_UDMH_LOOKUP_STATUS] (  [PACKAGE_NAME], [SOURCE_TABLE_NAME],[FILE_VERSION],[FILE_STATUS]) VALUES (N'PKG_XFM_LUT_ROOF_TYPE',N'TB_XFM_LUT_ROOF_TYPE',NULL, NULL)
INSERT [DBO].[TB_UDMH_LOOKUP_STATUS] (  [PACKAGE_NAME], [SOURCE_TABLE_NAME],[FILE_VERSION],[FILE_STATUS]) VALUES (N'PKG_XFM_LUT_S01_CLASS_TYPE',N'TB_XFM_LUT_S01_CLASS_TYPE',NULL, NULL)
INSERT [DBO].[TB_UDMH_LOOKUP_STATUS] (  [PACKAGE_NAME], [SOURCE_TABLE_NAME],[FILE_VERSION],[FILE_STATUS]) VALUES (N'PKG_XFM_LUT_S01_NEW_CLASS',N'TB_XFM_LUT_S01_NEW_CLASS',NULL, NULL)
INSERT [DBO].[TB_UDMH_LOOKUP_STATUS] (  [PACKAGE_NAME], [SOURCE_TABLE_NAME],[FILE_VERSION],[FILE_STATUS]) VALUES (N'PKG_XFM_LUT_S01_PROTYPE',N'TB_XFM_LUT_S01_PROTYPE',NULL, NULL)
INSERT [DBO].[TB_UDMH_LOOKUP_STATUS] (  [PACKAGE_NAME], [SOURCE_TABLE_NAME],[FILE_VERSION],[FILE_STATUS]) VALUES (N'PKG_XFM_LUT_SALE_METHOD',N'TB_XFM_LUT_SALE_METHOD',NULL, NULL)
INSERT [DBO].[TB_UDMH_LOOKUP_STATUS] (  [PACKAGE_NAME], [SOURCE_TABLE_NAME],[FILE_VERSION],[FILE_STATUS]) VALUES (N'PKG_XFM_LUT_SALE_STATUS',N'TB_XFM_LUT_SALE_STATUS',NULL, NULL)
INSERT [DBO].[TB_UDMH_LOOKUP_STATUS] (  [PACKAGE_NAME], [SOURCE_TABLE_NAME],[FILE_VERSION],[FILE_STATUS]) VALUES (N'PKG_XFM_LUT_SCHG_REAS',N'TB_XFM_LUT_SCHG_REAS',NULL, NULL)
INSERT [DBO].[TB_UDMH_LOOKUP_STATUS] (  [PACKAGE_NAME], [SOURCE_TABLE_NAME],[FILE_VERSION],[FILE_STATUS]) VALUES (N'PKG_XFM_LUT_SCR_BLUE_ACCOUNTNO',N'TB_XFM_LUT_SCR_BLUE_ACCOUNTNO',NULL, NULL)
INSERT [DBO].[TB_UDMH_LOOKUP_STATUS] (  [PACKAGE_NAME], [SOURCE_TABLE_NAME],[FILE_VERSION],[FILE_STATUS]) VALUES (N'PKG_XFM_LUT_SEC_TYPE',N'TB_XFM_LUT_SEC_TYPE',NULL, NULL)
INSERT [DBO].[TB_UDMH_LOOKUP_STATUS] (  [PACKAGE_NAME], [SOURCE_TABLE_NAME],[FILE_VERSION],[FILE_STATUS]) VALUES (N'PKG_XFM_LUT_SERVICELEVEL',N'TB_XFM_LUT_SERVICELEVEL',NULL, NULL)
INSERT [DBO].[TB_UDMH_LOOKUP_STATUS] (  [PACKAGE_NAME], [SOURCE_TABLE_NAME],[FILE_VERSION],[FILE_STATUS]) VALUES (N'PKG_XFM_LUT_TENURE',N'TB_XFM_LUT_TENURE',NULL, NULL)
INSERT [DBO].[TB_UDMH_LOOKUP_STATUS] (  [PACKAGE_NAME], [SOURCE_TABLE_NAME],[FILE_VERSION],[FILE_STATUS]) VALUES (N'PKG_XFM_LUT_TRACE_AGENT',N'TB_XFM_LUT_TRACE_AGENT',NULL, NULL)
INSERT [DBO].[TB_UDMH_LOOKUP_STATUS] (  [PACKAGE_NAME], [SOURCE_TABLE_NAME],[FILE_VERSION],[FILE_STATUS]) VALUES (N'PKG_XFM_LUT_TRACE_TYPE',N'TB_XFM_LUT_TRACE_TYPE',NULL, NULL)
INSERT [DBO].[TB_UDMH_LOOKUP_STATUS] (  [PACKAGE_NAME], [SOURCE_TABLE_NAME],[FILE_VERSION],[FILE_STATUS]) VALUES (N'PKG_XFM_LUT_TX',N'TB_XFM_LUT_TX',NULL, NULL)
INSERT [DBO].[TB_UDMH_LOOKUP_STATUS] (  [PACKAGE_NAME], [SOURCE_TABLE_NAME],[FILE_VERSION],[FILE_STATUS]) VALUES (N'PKG_XFM_LUT_USERCODE',N'TB_XFM_LUT_USERCODE',NULL, NULL)
INSERT [DBO].[TB_UDMH_LOOKUP_STATUS] (  [PACKAGE_NAME], [SOURCE_TABLE_NAME],[FILE_VERSION],[FILE_STATUS]) VALUES (N'PKG_XFM_LUT_VALTYPE',N'TB_XFM_LUT_VALTYPE',NULL, NULL)
INSERT [DBO].[TB_UDMH_LOOKUP_STATUS] (  [PACKAGE_NAME], [SOURCE_TABLE_NAME],[FILE_VERSION],[FILE_STATUS]) VALUES (N'PKG_XFM_LUT_WALL_TYPE',N'TB_XFM_LUT_WALL_TYPE',NULL, NULL)
INSERT [DBO].[TB_UDMH_LOOKUP_STATUS] (  [PACKAGE_NAME], [SOURCE_TABLE_NAME],[FILE_VERSION],[FILE_STATUS]) VALUES (N'PKG_XFM_LUT_WRNCDE',N'TB_XFM_LUT_WRNCDE',NULL, NULL)
INSERT [DBO].[TB_UDMH_LOOKUP_STATUS] (  [PACKAGE_NAME], [SOURCE_TABLE_NAME],[FILE_VERSION],[FILE_STATUS]) VALUES (N'PKG_XFM_LUT_YEAR_END',N'TB_XFM_LUT_YEAR_END',NULL, NULL)



IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[TB_UDMH_CHECKSUM]') AND TYPE IN (N'U'))
DROP TABLE [DBO].[TB_UDMH_CHECKSUM]

CREATE TABLE [DBO].[TB_UDMH_CHECKSUM]
(
	[ID] [INT] IDENTITY(1,1) NOT NULL,
	[MACHINENAME] [VARCHAR](50) NULL,
	[TRANCHENUMBER] [CHAR](2) NULL,
	[CHUNKNUMBER] [CHAR](2) NULL,
	[SOURCENAME] [VARCHAR](100) NULL,
	[CHECKSUM] [CHAR](50) NULL,
	[CHECKSUMCREATEDATE] [DATETIME] NULL
) 





IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[TB_UDMH_EXCEPTION_SYSTEM]') AND TYPE IN (N'U'))
DROP TABLE [DBO].[TB_UDMH_EXCEPTION_SYSTEM]

CREATE TABLE [DBO].[TB_UDMH_EXCEPTION_SYSTEM]
(
	[EXCEPT_ID] [INT] IDENTITY(1,1) NOT NULL,
	[EXCEPT_DATETIME] [DATETIME] NULL,
	[EXCEPT_TRANCHE] [VARCHAR](2) NULL,
	[EXCEPT_CHUNK] [VARCHAR](2) NULL,
	[EXCEPT_SRCSYSTEM] [VARCHAR](30) NULL,
	[EXCEPT_SRCKEY1] [VARCHAR](30) NULL,
	[EXCEPT_TARGETTYPE] [VARCHAR](50) NULL,
	[EXCEPT_MESSAGE] [VARCHAR](MAX) NULL
)


/* CREATION OF EXCEPTION TABLE*/
IF OBJECT_ID('TB_UDMH_EXCEPTION',(SELECT TYPE FROM SYS.OBJECTS WHERE NAME='TB_UDMH_EXCEPTION')) IS NOT NULL
DROP TABLE TB_UDMH_EXCEPTION

CREATE TABLE TB_UDMH_EXCEPTION
(
   EXCEPT_ID INT IDENTITY(1,1) NOT NULL
  ,EXCEPT_PACKAGE VARCHAR(100) NULL
  ,EXCEPT_CODE VARCHAR(50) NULL
  ,EXCEPT_DATETIME DATETIME DEFAULT GETDATE() 
  ,EXCEPT_ACCOUNT_NO VARCHAR(16) NULL
  ,EXCEPT_SEVERITY   CHAR(1) NULL
  ,EXCEPT_SRCFIELD_1 VARCHAR(100) NULL
  ,EXCEPT_SRCVALUE_1 VARCHAR(1000) NULL
  ,EXCEPT_SRCFIELD_2 VARCHAR(100) NULL
  ,EXCEPT_SRCVALUE_2 VARCHAR(1000) NULL
  ,EXCEPT_SRCFIELD_3 VARCHAR(100) NULL
  ,EXCEPT_SRCVALUE_3 VARCHAR(1000) NULL
  ,EXCEPT_SRCFIELD_4 VARCHAR(100) NULL
  ,EXCEPT_SRCVALUE_4 VARCHAR(1000) NULL
  ,EXCEPT_SRCFIELD_5 VARCHAR(100) NULL
  ,EXCEPT_SRCVALUE_5 VARCHAR(1000) NULL
  ,EXCEPT_SRCFIELD_6 VARCHAR(100) NULL
  ,EXCEPT_SRCVALUE_6 VARCHAR(1000) NULL
)


/* CREATION OF XML EXCEPTION TABLE WHICH WILL RAISE IN BASE QUERY */

IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[TB_UDMH_XML_EXCEPTION]') AND TYPE IN (N'U'))
DROP TABLE [DBO].[TB_UDMH_XML_EXCEPTION]

CREATE TABLE [DBO].[TB_UDMH_XML_EXCEPTION](
	[X02_UDMH_EXCEPTION] [XML] NULL
	,[EXCEPT_TARGETTYPE] [VARCHAR](7) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]



----CREATING  [UDMH_METRICS] TABLE IN [UDMH_METRICS] DB
--USE [UDMH_METRICS]


----THE BELOW SQL CODE TO CREATE THE UDMH_METRICS TABLE IN UDMH_METRICS DATABASE
--IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[UDMH_METRICS]') AND TYPE IN (N'U'))
--DROP TABLE [DBO].[UDMH_METRICS]

--CREATE TABLE [DBO].[UDMH_METRICS]
--( 
--    [RELEASE_NAME] [VARCHAR](100) NULL, 
--    [RECORD_TYPE] [VARCHAR](50) NULL, 
--    [TB_CNT] [INT] NULL, 
--    [FILE_CNT] [INT] NULL,
--    [RUN_TAG] [VARCHAR](8) NULL
--) 

END